export const LANGUAGE_ENGLISH = "en";
export const LANGUAGE_CHINESE_SIMPLIFIED = "zh-Hans";
export const LANGUAGE_JAPANESE = "ja";

export const SUPPORTED_LANGUAGES = Object.freeze([
  Object.freeze({ id: LANGUAGE_ENGLISH, label: "English", nativeLabel: "English" }),
  Object.freeze({ id: LANGUAGE_CHINESE_SIMPLIFIED, label: "Chinese (Simplified)", nativeLabel: "简体中文" }),
  Object.freeze({ id: LANGUAGE_JAPANESE, label: "Japanese", nativeLabel: "日本語" })
]);

const ENGLISH = Object.freeze({
  "language.english": "ENGLISH",
  "language.chineseSimplified": "简体中文",
  "language.japanese": "日本語",
  "options.title": "OPTIONS",
  "options.language": "LANGUAGE",
  "options.music": "MUSIC",
  "options.sfx": "SFX",
  "options.mute": "MUTE",
  "options.enterFullscreen": "ENTER FULLSCREEN",
  "options.exitFullscreen": "EXIT FULLSCREEN",
  "options.fullscreenUnavailable": "FULLSCREEN UNAVAILABLE",
  "options.returnToMainMenu": "RETURN TO MAIN MENU",
  "start.continue": "CONTINUE",
  "start.loading": "LOADING...",
  "start.newGame": "NEW GAME",
  "start.startGame": "START GAME",
  "start.shipBattle": "SHIP BATTLE",
  "start.pastVoyages": "PAST VOYAGES",
  "start.credits": "CREDITS",
  "start.saveUnreadable": "SAVE COULD NOT BE READ",
  "start.confirmNewGame": "ARE YOU SURE YOU WANT TO START A NEW GAME?",
  "start.confirmWarning": "THIS WILL END YOUR CURRENT VOYAGE.",
  "common.yes": "YES",
  "common.no": "NO",
  "common.next": "NEXT",
  "common.back": "BACK",
  "common.continue": "CONTINUE",
  "common.decline": "DECLINE",
  "common.close": "CLOSE",
  "common.page": "PAGE",
  "common.days": "DAYS",
  "common.day": "DAY",
  "common.loadingShip": "LOADING SHIP...",
  "captain.chart": "CAPTAIN'S CHART",
  "captain.shipLedger": "SHIP & LEDGER",
  "captain.politics": "POLITICS",
  "captain.discoveries": "DISCOVERIES",
  "captain.navigation": "NAVIGATION ICONS",
  "captain.sailingBasics": "SAILING BASICS",
  "navigation.none": "NO ACTIVE NAVIGATION ICONS",
  "navigation.gold": "GOLD",
  "navigation.blue": "BLUE",
  "navigation.gray": "GRAY",
  "navigation.teal": "TEAL",
  "navigation.foundColony": "FOUND THE COLONY",
  "navigation.resupplyColony": "RESUPPLY THE COLONY",
  "navigation.diplomaticMission": "DIPLOMATIC MISSION",
  "navigation.passengerMission": "PASSENGER MISSION",
  "navigation.deliveryMission": "DELIVERY MISSION",
  "navigation.activeMission": "ACTIVE MISSION",
  "navigation.explorerLead": "EXPLORER'S LEAD",
  "navigation.whiteWhaleSeen": "WHITE WHALE LAST SEEN",
  "navigation.reportPatron": "REPORT TO YOUR PATRON",
  "navigation.payFamilyDebt": "PAY THE FAMILY DEBT",
  "navigation.returnVictorious": "RETURN HOME VICTORIOUS",
  "navigation.returnHome": "RETURN HOME",
  "ship.vessel": "VESSEL",
  "ship.ledger": "LEDGER",
  "ship.inventory": "INVENTORY",
  "ship.captainLedger": "CAPTAIN'S LEDGER",
  "ship.shipInventory": "SHIP'S INVENTORY",
  "ship.hull": "HULL",
  "ship.crew": "CREW",
  "ship.propulsion": "PROPULSION",
  "ship.speed": "SPEED",
  "ship.acceleration": "ACCEL",
  "ship.turning": "TURNING",
  "ship.windward": "WINDWARD",
  "ship.seaworthy": "SEAWORTHY",
  "ship.water": "WATER",
  "ship.food": "FOOD",
  "ship.cargoHold": "CARGO HOLD",
  "ship.holdEmpty": "THE HOLD IS EMPTY",
  "ship.itemsDocuments": "ITEMS & DOCUMENTS",
  "ship.inventoryEmpty": "INVENTORY IS EMPTY",
  "ship.realizedPnl": "REALIZED P/L",
  "ship.cash": "CASH",
  "ship.date": "DATE",
  "ship.port": "PORT",
  "ship.entry": "ENTRY",
  "ship.amount": "AMOUNT",
  "ship.balance": "BAL",
  "ship.pnl": "P/L",
  "ship.type": "TYPE",
  "ship.detail": "DETAIL",
  "ship.manifest": "MANIFEST",
  "ship.held": "HELD",
  "ship.average": "AVG",
  "ship.doubloons": "DOUBLOONS",
  "ship.armament": "ARMAMENT",
  "ship.current": "CURRENT",
  "ship.new": "NEW",
  "ship.prize": "PRIZE",
  "ship.guns": "GUNS",
  "ship.arrows": "ARROWS",
  "ship.atWill": "AT WILL",
  "ship.oarNoDeadZone": "OAR / NO DEAD ZONE",
  "ship.oarSailUpwind": "OAR + SAIL / ROWS UPWIND",
  "ship.item": "ITEM",
  "ship.equipment": "EQUIPMENT",
  "ship.delivery": "DELIVERY",
  "ship.passenger": "PASSENGER",
  "ship.openingBalance": "OPENING BALANCE",
  "ship.aboard": "ABOARD",
  "ship.shipyardNew": "SHIPYARD / NEW VESSEL",
  "ship.surrenderedPrize": "SURRENDERED PRIZE",
  "discoveries.title": "DISCOVERIES",
  "discoveries.found": "FOUND",
  "discoveries.globeMapped": "GLOBE MAPPED",
  "discoveries.none": "NO DISCOVERIES YET",
  "politics.title": "POLITICAL CHART",
  "politics.ally": "ALLY",
  "politics.war": "WAR",
  "politics.neutral": "NEUTRAL",
  "politics.noContact": "NO CONTACT",
  "politics.stanceToward": "STANCE TOWARD",
  "politics.playerStanding": "PLAYER STANDING",
  "politics.power": "POWER",
  "politics.status": "STATUS",
  "politics.you": "YOU",
  "politics.latest": "LATEST",
  "politics.marque": "MARQUE",
  "politics.legendAlly": "A ALLY",
  "politics.legendWar": "W WAR",
  "politics.legendNeutral": "- NEUTRAL  . NO CONTACT",
  "politics.legendCompact": "- NEUT  . NONE",
  "politics.hostile": "HOSTILE",
  "politics.angry": "ANGRY",
  "politics.cold": "COLD",
  "politics.warm": "WARM",
  "politics.favored": "FAVORED",
  "politics.trusted": "TRUSTED",
  "faction.pirate": "PIRATE",
  "faction.england": "ENGLISH",
  "faction.scotland": "SCOTTISH",
  "faction.france": "FRENCH",
  "faction.spain": "SPANISH",
  "faction.portugal": "PORTUGUESE",
  "faction.habsburg": "HABSBURG",
  "faction.hungary": "HUNGARIAN",
  "faction.ottoman": "OTTOMAN",
  "faction.venice": "VENETIAN",
  "faction.genoa": "GENOESE",
  "faction.papalStates": "PAPAL",
  "faction.ming": "MING",
  "faction.aztec": "AZTEC",
  "faction.inca": "INCA",
  "faction.safavid": "SAFAVID",
  "faction.muscovy": "MUSCOVITE",
  "faction.polandLithuania": "POLISH-LITHUANIAN",
  "faction.denmarkNorway": "DANO-NORWEGIAN",
  "faction.songhai": "SONGHAI",
  "faction.morocco": "MOROCCAN",
  "faction.ethiopia": "ETHIOPIAN",
  "faction.vijayanagara": "VIJAYANAGARAN",
  "faction.gujarat": "GUJARATI",
  "faction.bengal": "BENGALI",
  "faction.delhi": "DELHI",
  "faction.ayutthaya": "AYUTTHAYAN",
  "faction.japan": "JAPANESE",
  "faction.joseon": "JOSEON",
  "good.hardtack": "Hardtack",
  "good.freshWater": "Fresh Water",
  "good.foragedFood": "Foraged Food",
  "good.grain": "Grain",
  "good.fish": "Fish",
  "good.whaleBlubber": "Whale Blubber",
  "good.beaverPelts": "Beaver Pelts",
  "good.cheese": "Cheese",
  "good.wine": "Wine",
  "good.oliveOil": "Olive Oil",
  "good.salt": "Salt",
  "good.sugar": "Sugar",
  "good.timber": "Timber",
  "good.wool": "Wool",
  "good.cotton": "Cotton",
  "good.flax": "Flax",
  "good.iron": "Iron",
  "good.copper": "Copper",
  "good.tin": "Tin",
  "good.arms": "Arms",
  "good.linenCloth": "Linen Cloth",
  "good.woolCloth": "Wool Cloth",
  "good.cottonCloth": "Cotton Cloth",
  "good.silk": "Silk",
  "good.silkCloth": "Silk Cloth",
  "good.pepper": "Pepper",
  "good.cinnamon": "Cinnamon",
  "good.cloves": "Cloves",
  "good.nutmeg": "Nutmeg",
  "good.tea": "Tea",
  "good.coffee": "Coffee",
  "good.cacao": "Cacao",
  "good.dyes": "Dyes",
  "good.porcelain": "Porcelain",
  "good.glassware": "Glassware",
  "good.carpets": "Carpets",
  "good.artwork": "Artwork",
  "good.perfume": "Perfume",
  "good.ivory": "Ivory",
  "good.silver": "Silver",
  "good.gold": "Gold",
  "voyages.title": "PAST VOYAGES",
  "voyages.register": "CAPTAINS' REGISTER",
  "voyages.voyages": "VOYAGES",
  "voyages.totalDays": "TOTAL DAYS",
  "voyages.longest": "LONGEST VOYAGE",
  "voyages.totalEarned": "TOTAL EARNED",
  "voyages.mostEarned": "MOST EARNED",
  "voyages.richestEnding": "RICHEST ENDING",
  "voyages.mostDiscoveries": "MOST DISCOVERIES",
  "voyages.winDeathQuitDemo": "WIN / DEATH / QUIT / DEMO",
  "voyages.none": "NO PAST VOYAGES YET",
  "voyages.home": "HOME",
  "voyages.resultGoal": "RESULT / GOAL",
  "voyages.lastVessel": "LAST VESSEL",
  "voyages.daysMapped": "DAYS / WORLD MAPPED",
  "voyages.earnedNet": "EARNED / NET",
  "voyages.finalTradePnl": "FINAL / TRADE PNL",
  "voyages.discoveryPortsWorld": "DISC / PORTS / WORLD",
  "voyages.questsMarques": "QUESTS / MARQUES",
  "voyages.crewLostPiracy": "CREW LOST / PIRACY",
  "voyages.fate": "FATE",
  "intro.papers": "CAPTAIN'S PAPERS",
  "intro.homePort": "HOME PORT",
  "intro.nationality": "NATIONALITY",
  "intro.born": "BORN",
  "intro.age": "AGE",
  "intro.sex": "SEX",
  "intro.male": "MALE",
  "intro.female": "FEMALE",
  "intro.begin": "BEGIN VOYAGE",
  "tutorial.turnSail": "TURN AND SAIL",
  "tutorial.upwind": "SAILING UPWIND",
  "tutorial.escapeShore": "ESCAPE THE SHORE",
  "tutorial.takeHelm": "TAKE THE HELM",
  "tutorial.pressHold": "PRESS + HOLD",
  "tutorial.tiltHold": "TILT + HOLD",
  "tutorial.touchHold": "TOUCH + HOLD",
  "tutorial.clickHold": "CLICK + HOLD",
  "tutorial.turnBow": "TURN THE BOW",
  "tutorial.wind": "WIND",
  "tutorial.tack": "TACK",
  "tutorial.haul": "HAUL",
  "tutorial.openWater": "OPEN WATER",
  "tutorial.touchSteer": "Touch and hold anywhere around your ship. The bow turns toward your finger. Keep holding while it sails.",
  "tutorial.mouseSteer": "Click and hold anywhere around your ship. The bow turns toward the pointer. Keep holding while it sails.",
  "tutorial.keyboardSteer": "Press and hold WASD or an arrow key. The bow turns toward that direction. Keep holding while it sails.",
  "tutorial.controllerSteer": "Tilt and hold the left stick. The bow turns toward that direction. Keep holding while it sails.",
  "tutorial.tacking": "Most sailing ships cannot point straight into the wind. Aim to either side, then cross back and forth. This zigzag is called tacking.",
  "tutorial.touchHaul": "If wind pins you against a riverbank or coast, touch and hold toward open water. Your crew will haul along the shore, very slowly.",
  "tutorial.mouseHaul": "If wind pins you against a riverbank or coast, click and hold toward open water. Your crew will haul along the shore, very slowly.",
  "tutorial.keyboardHaul": "If wind pins you against a riverbank or coast, hold a direction key toward open water. Your crew will haul along the shore, very slowly.",
  "tutorial.controllerHaul": "If wind pins you against a riverbank or coast, hold the left stick toward open water. Your crew will haul along the shore, very slowly.",
  "dialogue.leavePort": "LEAVE PORT",
  "dialogue.buy": "BUY",
  "dialogue.sell": "SELL",
  "dialogue.trade": "TRADE",
  "dialogue.accept": "ACCEPT",
  "dialogue.capital": "CAPITAL",
  "status.mapped": "MAPPED",
  "status.loading": "Loading Marque & Reprisal...",
  "aria.worldMap": "world map",
  "aria.shipBattleLake": "ship battle lake",
  "aria.canvas": "Marque & Reprisal {surface}, {width} by {height}"
});

const CHINESE_SIMPLIFIED = Object.freeze({
  "language.english": "英文",
  "language.chineseSimplified": "简体中文",
  "language.japanese": "日语",
  "options.title": "选项",
  "options.language": "语言",
  "options.music": "音乐",
  "options.sfx": "音效",
  "options.mute": "静音",
  "options.enterFullscreen": "进入全屏",
  "options.exitFullscreen": "退出全屏",
  "options.fullscreenUnavailable": "无法使用全屏",
  "options.returnToMainMenu": "返回主菜单",
  "start.continue": "继续航行",
  "start.loading": "读取中……",
  "start.newGame": "新游戏",
  "start.startGame": "开始游戏",
  "start.shipBattle": "海战",
  "start.pastVoyages": "往昔航程",
  "start.credits": "制作人员",
  "start.saveUnreadable": "无法读取存档",
  "start.confirmNewGame": "确定要开始新游戏吗？",
  "start.confirmWarning": "当前航程将会结束。",
  "common.yes": "是",
  "common.no": "否",
  "common.next": "下一页",
  "common.back": "返回",
  "common.continue": "继续",
  "common.decline": "婉拒",
  "common.close": "关闭",
  "common.page": "页",
  "common.days": "天",
  "common.day": "天",
  "common.loadingShip": "船只读取中……",
  "captain.chart": "船长海图",
  "captain.shipLedger": "船只与账簿",
  "captain.politics": "列国政局",
  "captain.discoveries": "发现记录",
  "captain.navigation": "航向标记",
  "captain.sailingBasics": "航海入门",
  "navigation.none": "目前没有航向标记",
  "navigation.gold": "金色",
  "navigation.blue": "蓝色",
  "navigation.gray": "灰色",
  "navigation.teal": "青色",
  "navigation.foundColony": "建立殖民地",
  "navigation.resupplyColony": "补给殖民地",
  "navigation.diplomaticMission": "外交任务",
  "navigation.passengerMission": "载客任务",
  "navigation.deliveryMission": "递送任务",
  "navigation.activeMission": "当前任务",
  "navigation.explorerLead": "探险线索",
  "navigation.whiteWhaleSeen": "白鲸最后目击地",
  "navigation.reportPatron": "向赞助人报告",
  "navigation.payFamilyDebt": "偿还家族债务",
  "navigation.returnVictorious": "凯旋归乡",
  "navigation.returnHome": "返回故乡",
  "ship.vessel": "船只",
  "ship.ledger": "账簿",
  "ship.inventory": "物品",
  "ship.captainLedger": "船长账簿",
  "ship.shipInventory": "船上物品",
  "ship.hull": "船体",
  "ship.crew": "船员",
  "ship.propulsion": "动力",
  "ship.speed": "速度",
  "ship.acceleration": "加速",
  "ship.turning": "转向",
  "ship.windward": "迎风",
  "ship.seaworthy": "适航",
  "ship.water": "淡水",
  "ship.food": "食物",
  "ship.cargoHold": "货舱",
  "ship.holdEmpty": "货舱为空",
  "ship.itemsDocuments": "物品与文书",
  "ship.inventoryEmpty": "没有物品",
  "ship.realizedPnl": "已结盈亏",
  "ship.cash": "现款",
  "ship.date": "日期",
  "ship.port": "港口",
  "ship.entry": "事项",
  "ship.amount": "金额",
  "ship.balance": "余额",
  "ship.pnl": "盈亏",
  "ship.type": "类型",
  "ship.detail": "详情",
  "ship.manifest": "货单",
  "ship.held": "持有",
  "ship.average": "均价",
  "ship.doubloons": "达布隆",
  "ship.armament": "武装",
  "ship.current": "现有",
  "ship.new": "新船",
  "ship.prize": "战利船",
  "ship.guns": "火炮",
  "ship.arrows": "弓箭",
  "ship.atWill": "随时可用",
  "ship.oarNoDeadZone": "船桨／无迎风死区",
  "ship.oarSailUpwind": "桨帆并用／可逆风划行",
  "ship.item": "物品",
  "ship.equipment": "装备",
  "ship.delivery": "递送",
  "ship.passenger": "乘客",
  "ship.openingBalance": "期初余额",
  "ship.aboard": "船上",
  "ship.shipyardNew": "船厂／新船",
  "ship.surrenderedPrize": "受降战利船",
  "discoveries.title": "发现记录",
  "discoveries.found": "已发现",
  "discoveries.globeMapped": "世界测绘",
  "discoveries.none": "尚无发现",
  "politics.title": "列国政局",
  "politics.ally": "同盟",
  "politics.war": "战争",
  "politics.neutral": "中立",
  "politics.noContact": "未接触",
  "politics.stanceToward": "各国立场",
  "politics.playerStanding": "对你态度",
  "politics.power": "势力",
  "politics.status": "关系",
  "politics.you": "你",
  "politics.latest": "最新",
  "politics.marque": "私掠许可",
  "politics.legendAlly": "A 同盟",
  "politics.legendWar": "W 战争",
  "politics.legendNeutral": "- 中立  . 未接触",
  "politics.legendCompact": "- 中立  . 未知",
  "politics.hostile": "敌视",
  "politics.angry": "愤怒",
  "politics.cold": "冷淡",
  "politics.warm": "友善",
  "politics.favored": "器重",
  "politics.trusted": "信任",
  "faction.pirate": "海盗",
  "faction.england": "英格兰",
  "faction.scotland": "苏格兰",
  "faction.france": "法兰西",
  "faction.spain": "西班牙",
  "faction.portugal": "葡萄牙",
  "faction.habsburg": "哈布斯堡",
  "faction.hungary": "匈牙利",
  "faction.ottoman": "奥斯曼",
  "faction.venice": "威尼斯",
  "faction.genoa": "热那亚",
  "faction.papalStates": "教宗国",
  "faction.ming": "明朝",
  "faction.aztec": "阿兹特克",
  "faction.inca": "印加",
  "faction.safavid": "萨法维",
  "faction.muscovy": "莫斯科公国",
  "faction.polandLithuania": "波兰-立陶宛",
  "faction.denmarkNorway": "丹麦-挪威",
  "faction.songhai": "桑海",
  "faction.morocco": "摩洛哥",
  "faction.ethiopia": "埃塞俄比亚",
  "faction.vijayanagara": "毗奢耶那伽罗",
  "faction.gujarat": "古吉拉特",
  "faction.bengal": "孟加拉",
  "faction.delhi": "德里",
  "faction.ayutthaya": "阿瑜陀耶",
  "faction.japan": "日本",
  "faction.joseon": "朝鲜",
  "good.hardtack": "硬饼干",
  "good.freshWater": "淡水",
  "good.foragedFood": "采集食物",
  "good.grain": "谷物",
  "good.fish": "鱼",
  "good.whaleBlubber": "鲸脂",
  "good.beaverPelts": "海狸皮",
  "good.cheese": "奶酪",
  "good.wine": "葡萄酒",
  "good.oliveOil": "橄榄油",
  "good.salt": "盐",
  "good.sugar": "糖",
  "good.timber": "木材",
  "good.wool": "羊毛",
  "good.cotton": "棉花",
  "good.flax": "亚麻",
  "good.iron": "铁",
  "good.copper": "铜",
  "good.tin": "锡",
  "good.arms": "兵器",
  "good.linenCloth": "亚麻布",
  "good.woolCloth": "呢绒",
  "good.cottonCloth": "棉布",
  "good.silk": "生丝",
  "good.silkCloth": "丝绸",
  "good.pepper": "胡椒",
  "good.cinnamon": "肉桂",
  "good.cloves": "丁香",
  "good.nutmeg": "肉豆蔻",
  "good.tea": "茶叶",
  "good.coffee": "咖啡",
  "good.cacao": "可可",
  "good.dyes": "染料",
  "good.porcelain": "瓷器",
  "good.glassware": "玻璃器皿",
  "good.carpets": "地毯",
  "good.artwork": "艺术品",
  "good.perfume": "香水",
  "good.ivory": "象牙",
  "good.silver": "白银",
  "good.gold": "黄金",
  "voyages.title": "往昔航程",
  "voyages.register": "历任船长名录",
  "voyages.voyages": "航程次数",
  "voyages.totalDays": "累计天数",
  "voyages.longest": "最长航程",
  "voyages.totalEarned": "总收入",
  "voyages.mostEarned": "单程最高收入",
  "voyages.richestEnding": "最高结余",
  "voyages.mostDiscoveries": "单程最多发现",
  "voyages.winDeathQuitDemo": "胜利／死亡／退出／试玩",
  "voyages.none": "尚无往昔航程",
  "voyages.home": "故乡",
  "voyages.resultGoal": "结局／目标",
  "voyages.lastVessel": "最后船只",
  "voyages.daysMapped": "天数／世界测绘",
  "voyages.earnedNet": "收入／净额",
  "voyages.finalTradePnl": "结余／贸易盈亏",
  "voyages.discoveryPortsWorld": "发现／港口／环球",
  "voyages.questsMarques": "任务／私掠许可",
  "voyages.crewLostPiracy": "阵亡船员／海盗行为",
  "voyages.fate": "结局",
  "intro.papers": "船长文书",
  "intro.homePort": "故乡港口",
  "intro.nationality": "国籍",
  "intro.born": "出生",
  "intro.age": "年龄",
  "intro.sex": "性别",
  "intro.male": "男",
  "intro.female": "女",
  "intro.begin": "扬帆启程",
  "tutorial.turnSail": "转向与航行",
  "tutorial.upwind": "逆风航行",
  "tutorial.escapeShore": "脱离岸边",
  "tutorial.takeHelm": "接掌船舵",
  "tutorial.pressHold": "按住按键",
  "tutorial.tiltHold": "推住摇杆",
  "tutorial.touchHold": "触摸并按住",
  "tutorial.clickHold": "点击并按住",
  "tutorial.turnBow": "转动船头",
  "tutorial.wind": "风向",
  "tutorial.tack": "抢风",
  "tutorial.haul": "拖船",
  "tutorial.openWater": "开阔水面",
  "tutorial.touchSteer": "触摸并按住船只周围。船头会转向手指。航行时请继续按住。",
  "tutorial.mouseSteer": "点击并按住船只周围。船头会转向指针。航行时请继续按住。",
  "tutorial.keyboardSteer": "按住WASD或方向键。船头会转向该方向。航行时请继续按住。",
  "tutorial.controllerSteer": "倾斜并按住左摇杆。船头会转向该方向。航行时请继续按住。",
  "tutorial.tacking": "多数帆船无法直迎风向。先驶向风的一侧，再来回穿越风向。这种之字航法叫作抢风航行。",
  "tutorial.touchHaul": "若风把船困在河岸或海岸，朝开阔水面触摸并按住。船员会沿岸缓慢拖船。",
  "tutorial.mouseHaul": "若风把船困在河岸或海岸，朝开阔水面点击并按住。船员会沿岸缓慢拖船。",
  "tutorial.keyboardHaul": "若风把船困在河岸或海岸，按住朝开阔水面的方向键。船员会沿岸缓慢拖船。",
  "tutorial.controllerHaul": "若风把船困在河岸或海岸，朝开阔水面按住左摇杆。船员会沿岸缓慢拖船。",
  "dialogue.leavePort": "离开港口",
  "dialogue.buy": "购买",
  "dialogue.sell": "出售",
  "dialogue.trade": "贸易",
  "dialogue.accept": "接受",
  "dialogue.capital": "首都",
  "status.mapped": "已测绘",
  "status.loading": "《Marque & Reprisal》读取中……",
  "aria.worldMap": "世界地图",
  "aria.shipBattleLake": "海战水域",
  "aria.canvas": "Marque & Reprisal {surface}，{width}乘{height}"
});

const JAPANESE = Object.freeze({
  "language.english": "英語",
  "language.chineseSimplified": "簡体字中国語",
  "language.japanese": "日本語",
  "options.title": "オプション",
  "options.language": "言語",
  "options.music": "音楽",
  "options.sfx": "効果音",
  "options.mute": "ミュート",
  "options.enterFullscreen": "全画面にする",
  "options.exitFullscreen": "全画面を終了",
  "options.fullscreenUnavailable": "全画面は使用不可",
  "options.returnToMainMenu": "メインメニューへ",
  "start.continue": "航海を続ける",
  "start.loading": "読み込み中……",
  "start.newGame": "ニューゲーム",
  "start.startGame": "ゲーム開始",
  "start.shipBattle": "海戦",
  "start.pastVoyages": "過去の航海",
  "start.credits": "クレジット",
  "start.saveUnreadable": "セーブを読めません",
  "start.confirmNewGame": "新しいゲームを始めますか？",
  "start.confirmWarning": "現在の航海は終了します。",
  "common.yes": "はい",
  "common.no": "いいえ",
  "common.next": "次へ",
  "common.back": "戻る",
  "common.continue": "続ける",
  "common.decline": "断る",
  "common.close": "閉じる",
  "common.page": "ページ",
  "common.days": "日",
  "common.day": "日",
  "common.loadingShip": "船を読み込み中……",
  "captain.chart": "船長の海図",
  "captain.shipLedger": "船と帳簿",
  "captain.politics": "外交情勢",
  "captain.discoveries": "発見",
  "captain.navigation": "航路マーカー",
  "captain.sailingBasics": "航海の基本",
  "navigation.none": "有効な航路マーカーなし",
  "navigation.gold": "金",
  "navigation.blue": "青",
  "navigation.gray": "灰",
  "navigation.teal": "青緑",
  "navigation.foundColony": "植民地を建設",
  "navigation.resupplyColony": "植民地へ補給",
  "navigation.diplomaticMission": "外交任務",
  "navigation.passengerMission": "旅客任務",
  "navigation.deliveryMission": "配達任務",
  "navigation.activeMission": "現在の任務",
  "navigation.explorerLead": "探検の手掛かり",
  "navigation.whiteWhaleSeen": "白鯨の最終目撃地",
  "navigation.reportPatron": "後援者に報告",
  "navigation.payFamilyDebt": "家の借金を返済",
  "navigation.returnVictorious": "勝利して帰郷",
  "navigation.returnHome": "帰郷",
  "ship.vessel": "船",
  "ship.ledger": "帳簿",
  "ship.inventory": "所持品",
  "ship.captainLedger": "船長の帳簿",
  "ship.shipInventory": "船の所持品",
  "ship.hull": "船体",
  "ship.crew": "船員",
  "ship.propulsion": "推進",
  "ship.speed": "速力",
  "ship.acceleration": "加速",
  "ship.turning": "旋回",
  "ship.windward": "風上性能",
  "ship.seaworthy": "耐航性",
  "ship.water": "水",
  "ship.food": "食料",
  "ship.cargoHold": "船倉",
  "ship.holdEmpty": "船倉は空",
  "ship.itemsDocuments": "品物と書類",
  "ship.inventoryEmpty": "所持品なし",
  "ship.realizedPnl": "確定損益",
  "ship.cash": "現金",
  "ship.date": "日付",
  "ship.port": "港",
  "ship.entry": "内容",
  "ship.amount": "金額",
  "ship.balance": "残高",
  "ship.pnl": "損益",
  "ship.type": "種別",
  "ship.detail": "詳細",
  "ship.manifest": "積荷",
  "ship.held": "所持",
  "ship.average": "平均",
  "ship.doubloons": "ダブロン",
  "ship.armament": "武装",
  "ship.current": "現在",
  "ship.new": "新船",
  "ship.prize": "戦利船",
  "ship.guns": "大砲",
  "ship.arrows": "矢",
  "ship.atWill": "射撃可能",
  "ship.oarNoDeadZone": "櫂走／風上死角なし",
  "ship.oarSailUpwind": "櫂帆併用／風上では櫂",
  "ship.item": "品物",
  "ship.equipment": "装備",
  "ship.delivery": "配達",
  "ship.passenger": "乗客",
  "ship.openingBalance": "開始残高",
  "ship.aboard": "船上",
  "ship.shipyardNew": "造船所／新船",
  "ship.surrenderedPrize": "降伏した戦利船",
  "discoveries.title": "発見",
  "discoveries.found": "発見数",
  "discoveries.globeMapped": "世界踏破",
  "discoveries.none": "まだ発見なし",
  "politics.title": "外交情勢",
  "politics.ally": "同盟",
  "politics.war": "戦争",
  "politics.neutral": "中立",
  "politics.noContact": "未接触",
  "politics.stanceToward": "各国の姿勢",
  "politics.playerStanding": "あなたへの評価",
  "politics.power": "勢力",
  "politics.status": "関係",
  "politics.you": "自分",
  "politics.latest": "最新",
  "politics.marque": "私掠免許",
  "politics.legendAlly": "A 同盟",
  "politics.legendWar": "W 戦争",
  "politics.legendNeutral": "- 中立  . 未接触",
  "politics.legendCompact": "- 中立  . 不明",
  "politics.hostile": "敵対",
  "politics.angry": "激怒",
  "politics.cold": "冷淡",
  "politics.warm": "好意",
  "politics.favored": "厚遇",
  "politics.trusted": "信頼",
  "faction.pirate": "海賊",
  "faction.england": "イングランド",
  "faction.scotland": "スコットランド",
  "faction.france": "フランス",
  "faction.spain": "スペイン",
  "faction.portugal": "ポルトガル",
  "faction.habsburg": "ハプスブルク",
  "faction.hungary": "ハンガリー",
  "faction.ottoman": "オスマン",
  "faction.venice": "ヴェネツィア",
  "faction.genoa": "ジェノヴァ",
  "faction.papalStates": "教皇領",
  "faction.ming": "明",
  "faction.aztec": "アステカ",
  "faction.inca": "インカ",
  "faction.safavid": "サファヴィー",
  "faction.muscovy": "モスクワ大公国",
  "faction.polandLithuania": "ポーランド・リトアニア",
  "faction.denmarkNorway": "デンマーク・ノルウェー",
  "faction.songhai": "ソンガイ",
  "faction.morocco": "モロッコ",
  "faction.ethiopia": "エチオピア",
  "faction.vijayanagara": "ヴィジャヤナガル",
  "faction.gujarat": "グジャラート",
  "faction.bengal": "ベンガル",
  "faction.delhi": "デリー",
  "faction.ayutthaya": "アユタヤ",
  "faction.japan": "日本",
  "faction.joseon": "朝鮮",
  "good.hardtack": "乾パン",
  "good.freshWater": "真水",
  "good.foragedFood": "採集食料",
  "good.grain": "穀物",
  "good.fish": "魚",
  "good.whaleBlubber": "鯨脂",
  "good.beaverPelts": "ビーバー毛皮",
  "good.cheese": "チーズ",
  "good.wine": "ワイン",
  "good.oliveOil": "オリーブ油",
  "good.salt": "塩",
  "good.sugar": "砂糖",
  "good.timber": "木材",
  "good.wool": "羊毛",
  "good.cotton": "綿",
  "good.flax": "亜麻",
  "good.iron": "鉄",
  "good.copper": "銅",
  "good.tin": "錫",
  "good.arms": "武器",
  "good.linenCloth": "リネン布",
  "good.woolCloth": "毛織物",
  "good.cottonCloth": "綿布",
  "good.silk": "生糸",
  "good.silkCloth": "絹織物",
  "good.pepper": "胡椒",
  "good.cinnamon": "シナモン",
  "good.cloves": "クローブ",
  "good.nutmeg": "ナツメグ",
  "good.tea": "茶",
  "good.coffee": "コーヒー",
  "good.cacao": "カカオ",
  "good.dyes": "染料",
  "good.porcelain": "磁器",
  "good.glassware": "ガラス器",
  "good.carpets": "絨毯",
  "good.artwork": "美術品",
  "good.perfume": "香水",
  "good.ivory": "象牙",
  "good.silver": "銀",
  "good.gold": "金",
  "voyages.title": "過去の航海",
  "voyages.register": "歴代船長名簿",
  "voyages.voyages": "航海回数",
  "voyages.totalDays": "合計日数",
  "voyages.longest": "最長航海",
  "voyages.totalEarned": "総収入",
  "voyages.mostEarned": "最高収入",
  "voyages.richestEnding": "最高残高",
  "voyages.mostDiscoveries": "最多発見",
  "voyages.winDeathQuitDemo": "勝利／死亡／中断／体験版",
  "voyages.none": "過去の航海なし",
  "voyages.home": "故郷",
  "voyages.resultGoal": "結果／目標",
  "voyages.lastVessel": "最後の船",
  "voyages.daysMapped": "日数／世界踏破",
  "voyages.earnedNet": "収入／純益",
  "voyages.finalTradePnl": "残高／交易損益",
  "voyages.discoveryPortsWorld": "発見／港／世界",
  "voyages.questsMarques": "任務／私掠免許",
  "voyages.crewLostPiracy": "船員喪失／海賊行為",
  "voyages.fate": "運命",
  "intro.papers": "船長の書類",
  "intro.homePort": "母港",
  "intro.nationality": "国籍",
  "intro.born": "生年月日",
  "intro.age": "年齢",
  "intro.sex": "性別",
  "intro.male": "男",
  "intro.female": "女",
  "intro.begin": "出航",
  "tutorial.turnSail": "方向転換と帆走",
  "tutorial.upwind": "風上へ進む",
  "tutorial.escapeShore": "岸から脱出",
  "tutorial.takeHelm": "舵を取る",
  "tutorial.pressHold": "長押し",
  "tutorial.tiltHold": "スティックを倒す",
  "tutorial.touchHold": "タッチ長押し",
  "tutorial.clickHold": "クリック長押し",
  "tutorial.turnBow": "船首を回す",
  "tutorial.wind": "風向",
  "tutorial.tack": "タッキング",
  "tutorial.haul": "曳航",
  "tutorial.openWater": "開水面",
  "tutorial.touchSteer": "船の周囲をタッチして長押しします。船首が指の方向へ向きます。航行中も押し続けてください。",
  "tutorial.mouseSteer": "船の周囲をクリックして長押しします。船首がポインターの方向へ向きます。航行中も押し続けてください。",
  "tutorial.keyboardSteer": "WASDまたは矢印キーを長押しします。船首がその方向へ向きます。航行中も押し続けてください。",
  "tutorial.controllerSteer": "左スティックを倒したままにします。船首がその方向へ向きます。航行中も倒し続けてください。",
  "tutorial.tacking": "ほとんどの帆船は風上へ直進できません。風向の左右どちらかへ進み、交互に切り返してください。このジグザグ航法をタッキングと呼びます。",
  "tutorial.touchHaul": "風で川岸や海岸に押し付けられたら、開水面の方向をタッチして長押しします。船員が岸沿いにゆっくり船を曳きます。",
  "tutorial.mouseHaul": "風で川岸や海岸に押し付けられたら、開水面の方向をクリックして長押しします。船員が岸沿いにゆっくり船を曳きます。",
  "tutorial.keyboardHaul": "風で川岸や海岸に押し付けられたら、開水面へ向かう方向キーを長押しします。船員が岸沿いにゆっくり船を曳きます。",
  "tutorial.controllerHaul": "風で川岸や海岸に押し付けられたら、左スティックを開水面へ倒し続けます。船員が岸沿いにゆっくり船を曳きます。",
  "dialogue.leavePort": "出港",
  "dialogue.buy": "購入",
  "dialogue.sell": "売却",
  "dialogue.trade": "交易",
  "dialogue.accept": "引き受ける",
  "dialogue.capital": "首都",
  "status.mapped": "踏破済み",
  "status.loading": "『Marque & Reprisal』読み込み中……",
  "aria.worldMap": "世界地図",
  "aria.shipBattleLake": "海戦水域",
  "aria.canvas": "Marque & Reprisal {surface}、{width}×{height}"
});

const CATALOGS = Object.freeze({
  [LANGUAGE_ENGLISH]: ENGLISH,
  [LANGUAGE_CHINESE_SIMPLIFIED]: CHINESE_SIMPLIFIED,
  [LANGUAGE_JAPANESE]: JAPANESE
});

const ENGLISH_PHRASE_KEYS = Object.freeze(new Map(
  Object.entries(ENGLISH).map(([key, value]) => [value, key])
));

const EMBEDDED_PHRASES = Object.freeze(
  Object.entries(ENGLISH)
    .filter(([key]) => key.startsWith("good."))
    .sort((left, right) => right[1].length - left[1].length)
    .map(([key, value]) => Object.freeze({
      key,
      expression: new RegExp(escapeRegularExpression(value), "gi")
    }))
);

const DYNAMIC_PATTERNS = Object.freeze([
  dynamicPattern(/^PAGE (\d+)\/(\d+)$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, current, total) => `第${current}/${total}页`,
    [LANGUAGE_JAPANESE]: (_match, current, total) => `${current}/${total}頁`
  }),
  dynamicPattern(/^VOYAGE (\d+)$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, number) => `第${number}次航程`,
    [LANGUAGE_JAPANESE]: (_match, number) => `第${number}航海`
  }),
  dynamicPattern(/^MAPPED (.+)$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, value) => `已测绘 ${value}`,
    [LANGUAGE_JAPANESE]: (_match, value) => `踏破済み ${value}`
  }),
  dynamicPattern(/^MANIFEST (\d+)\/(\d+)$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, current, total) => `货单 ${current}/${total}`,
    [LANGUAGE_JAPANESE]: (_match, current, total) => `積荷 ${current}/${total}`
  }),
  dynamicPattern(/^LEDGER (\d+)\/(\d+)$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, current, total) => `账簿 ${current}/${total}`,
    [LANGUAGE_JAPANESE]: (_match, current, total) => `帳簿 ${current}/${total}`
  }),
  dynamicPattern(/^INVENTORY (\d+)\/(\d+)$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, current, total) => `物品 ${current}/${total}`,
    [LANGUAGE_JAPANESE]: (_match, current, total) => `所持品 ${current}/${total}`
  }),
  dynamicPattern(/^WATER (.+)D$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, value) => `淡水 ${value}天`,
    [LANGUAGE_JAPANESE]: (_match, value) => `水 ${value}日`
  }),
  dynamicPattern(/^FOOD (.+)D$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, value) => `食物 ${value}天`,
    [LANGUAGE_JAPANESE]: (_match, value) => `食料 ${value}日`
  }),
  dynamicPattern(/^(\d+) DAYS$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, value) => `${value}天`,
    [LANGUAGE_JAPANESE]: (_match, value) => `${value}日`
  }),
  dynamicPattern(/^(\d+) HELD$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, value) => `持有 ${value}`,
    [LANGUAGE_JAPANESE]: (_match, value) => `${value}点`
  }),
  dynamicPattern(/^CASH (.+) DB$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, value) => `现款 ${value}`,
    [LANGUAGE_JAPANESE]: (_match, value) => `現金 ${value}`
  }),
  dynamicPattern(/^P\/L (.+) DB$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, value) => `盈亏 ${value}`,
    [LANGUAGE_JAPANESE]: (_match, value) => `損益 ${value}`
  }),
  dynamicPattern(/^REALIZED P\/L (.+) DB$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, value) => `已结盈亏 ${value}`,
    [LANGUAGE_JAPANESE]: (_match, value) => `確定損益 ${value}`
  }),
  dynamicPattern(/^AVG --$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: () => "均价 --",
    [LANGUAGE_JAPANESE]: () => "平均 --"
  }),
  dynamicPattern(/^AVG (.+) DB$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, value) => `均价 ${value}`,
    [LANGUAGE_JAPANESE]: (_match, value) => `平均 ${value}`
  }),
  dynamicPattern(/^(.+) RATIONS$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, value) => `${value}份口粮`,
    [LANGUAGE_JAPANESE]: (_match, value) => `${value}食`
  }),
  dynamicPattern(/^SAIL \/ (.+) DEG$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, value) => `风帆／迎风死区${value}度`,
    [LANGUAGE_JAPANESE]: (_match, value) => `帆走／風上死角${value}度`
  }),
  dynamicPattern(/^(.+) DOUBLOONS$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, value) => `${value} 达布隆`,
    [LANGUAGE_JAPANESE]: (_match, value) => `${value}ダブロン`
  }),
  dynamicPattern(/^LATEST (.+)$/, {
    [LANGUAGE_CHINESE_SIMPLIFIED]: (_match, value) => `最新：${value}`,
    [LANGUAGE_JAPANESE]: (_match, value) => `最新：${value}`
  })
]);

export function normalizeLanguage(value, fallback = LANGUAGE_ENGLISH) {
  if (SUPPORTED_LANGUAGES.some((entry) => entry.id === value)) return value;
  if (typeof value === "string") {
    const normalized = value.trim().toLowerCase();
    if (normalized === "zh" || normalized === "zh-cn" || normalized === "zh-sg" || normalized === "zh-hans") {
      return LANGUAGE_CHINESE_SIMPLIFIED;
    }
    if (normalized === "ja" || normalized.startsWith("ja-")) return LANGUAGE_JAPANESE;
    if (normalized === "en" || normalized.startsWith("en-")) return LANGUAGE_ENGLISH;
  }
  if (fallback === value) return LANGUAGE_ENGLISH;
  return normalizeLanguage(fallback, LANGUAGE_ENGLISH);
}

export function translate(language, key, replacements = {}) {
  const locale = normalizeLanguage(language);
  const template = CATALOGS[locale][key] ?? ENGLISH[key];
  if (template === undefined) throw new Error(`Unknown localization key: ${key}`);
  return interpolate(template, replacements);
}

export function localizeText(language, text) {
  if (typeof text !== "string") throw new Error(`Localized text must be a string: ${text}`);
  const locale = normalizeLanguage(language);
  if (locale === LANGUAGE_ENGLISH || text.length === 0) return text;
  const exactKey = ENGLISH_PHRASE_KEYS.get(text);
  if (exactKey) return translate(locale, exactKey);
  for (const pattern of DYNAMIC_PATTERNS) {
    const match = text.match(pattern.expression);
    const renderer = pattern.renderers[locale];
    if (match && renderer) return localizeEmbeddedPhrases(locale, renderer(...match));
  }
  return localizeEmbeddedPhrases(locale, text);
}

export function languageFontProfile(language) {
  const locale = normalizeLanguage(language);
  if (locale === LANGUAGE_CHINESE_SIMPLIFIED || locale === LANGUAGE_JAPANESE) {
    return Object.freeze({
      smallFont: '12px "zpix", monospace',
      dialogueFont: '12px "zpix", monospace',
      fontSize: 12,
      lineHeight: 14,
      detailLineHeight: 14,
      tableRowHeight: 14
    });
  }
  return Object.freeze({
    smallFont: '8px "Silkscreen", monospace',
    dialogueFont: '8px "Dogica", monospace',
    fontSize: 8,
    lineHeight: 10,
    detailLineHeight: 10,
    tableRowHeight: 11
  });
}

export function languageHasCjkMetrics(language) {
  const locale = normalizeLanguage(language);
  return locale === LANGUAGE_CHINESE_SIMPLIFIED || locale === LANGUAGE_JAPANESE;
}

export function textContainsCjk(text) {
  return /[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]/u.test(String(text));
}

export function nextLanguage(language, direction = 1) {
  if (!Number.isInteger(direction) || direction === 0) {
    throw new Error(`Language step must be a non-zero integer: ${direction}`);
  }
  const current = normalizeLanguage(language);
  const index = SUPPORTED_LANGUAGES.findIndex((entry) => entry.id === current);
  const nextIndex = (index + Math.sign(direction) + SUPPORTED_LANGUAGES.length) % SUPPORTED_LANGUAGES.length;
  return SUPPORTED_LANGUAGES[nextIndex].id;
}

export function localizationCatalog(language) {
  return CATALOGS[normalizeLanguage(language)];
}

export function languageNativeLabel(language) {
  const locale = normalizeLanguage(language);
  const entry = SUPPORTED_LANGUAGES.find((candidate) => candidate.id === locale);
  if (!entry) throw new Error(`Supported language is missing metadata: ${locale}`);
  return entry.nativeLabel;
}

function dynamicPattern(expression, renderers) {
  return Object.freeze({ expression, renderers: Object.freeze(renderers) });
}

function localizeEmbeddedPhrases(locale, text) {
  let localized = text;
  for (const phrase of EMBEDDED_PHRASES) {
    localized = localized.replace(phrase.expression, translate(locale, phrase.key));
  }
  return localized;
}

function escapeRegularExpression(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function interpolate(template, replacements) {
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (_match, key) => {
    if (!(key in replacements)) throw new Error(`Missing localization replacement: ${key}`);
    return String(replacements[key]);
  });
}
