import GERMAN from "./locales/de.js";
import SPANISH from "./locales/es.js";
import FRENCH from "./locales/fr.js";
import KOREAN from "./locales/ko.js";
import POLISH from "./locales/pl.js";
import PORTUGUESE_BRAZIL from "./locales/pt-BR.js";
import RUSSIAN from "./locales/ru.js";
import CHINESE_TRADITIONAL from "./locales/zh-Hant.js";
import { localizeGameplayScreenText } from "./screenTextLocalization.js";

export const LANGUAGE_ENGLISH = "en";
export const LANGUAGE_CHINESE_SIMPLIFIED = "zh-Hans";
export const LANGUAGE_RUSSIAN = "ru";
export const LANGUAGE_SPANISH = "es";
export const LANGUAGE_PORTUGUESE_BRAZIL = "pt-BR";
export const LANGUAGE_JAPANESE = "ja";
export const LANGUAGE_GERMAN = "de";
export const LANGUAGE_FRENCH = "fr";
export const LANGUAGE_POLISH = "pl";
export const LANGUAGE_CHINESE_TRADITIONAL = "zh-Hant";
export const LANGUAGE_KOREAN = "ko";

export const SUPPORTED_LANGUAGES = Object.freeze([
  Object.freeze({ id: LANGUAGE_ENGLISH, label: "English", nativeLabel: "English" }),
  Object.freeze({ id: LANGUAGE_CHINESE_SIMPLIFIED, label: "Chinese (Simplified)", nativeLabel: "简体中文" }),
  Object.freeze({ id: LANGUAGE_RUSSIAN, label: "Russian", nativeLabel: "Русский" }),
  Object.freeze({ id: LANGUAGE_SPANISH, label: "Spanish", nativeLabel: "Español" }),
  Object.freeze({ id: LANGUAGE_PORTUGUESE_BRAZIL, label: "Portuguese (Brazil)", nativeLabel: "Português (Brasil)" }),
  Object.freeze({ id: LANGUAGE_JAPANESE, label: "Japanese", nativeLabel: "日本語" }),
  Object.freeze({ id: LANGUAGE_GERMAN, label: "German", nativeLabel: "Deutsch" }),
  Object.freeze({ id: LANGUAGE_FRENCH, label: "French", nativeLabel: "Français" }),
  Object.freeze({ id: LANGUAGE_POLISH, label: "Polish", nativeLabel: "Polski" }),
  Object.freeze({ id: LANGUAGE_CHINESE_TRADITIONAL, label: "Chinese (Traditional)", nativeLabel: "繁體中文" }),
  Object.freeze({ id: LANGUAGE_KOREAN, label: "Korean", nativeLabel: "한국어" })
]);

const ENGLISH = Object.freeze({
  "language.english": "ENGLISH",
  "language.chineseSimplified": "简体中文",
  "language.russian": "РУССКИЙ",
  "language.spanish": "ESPAÑOL",
  "language.portugueseBrazil": "PORTUGUÊS (BRASIL)",
  "language.japanese": "日本語",
  "language.german": "DEUTSCH",
  "language.french": "FRANÇAIS",
  "language.polish": "POLSKI",
  "language.chineseTraditional": "繁體中文",
  "language.korean": "한국어",
  "options.title": "OPTIONS",
  "options.language": "LANGUAGE",
  "options.controllerIcons": "CONTROLLER ICONS",
  "options.controllerIcons.automatic": "AUTOMATIC",
  "options.controllerIcons.xbox": "XBOX",
  "options.controllerIcons.playstation": "PLAYSTATION",
  "options.controllerIcons.nintendo": "NINTENDO",
  "options.controllerIcons.generic": "GENERIC",
  "options.controlScheme": "CONTROL SCHEME",
  "options.controlScheme.title": "STEERING CONTROLS",
  "options.controlScheme.absolute": "ABSOLUTE",
  "options.controlScheme.relative": "RELATIVE",
  "options.controlScheme.absoluteDetail": "DIRECTIONS POINT THE BOW",
  "options.controlScheme.relativeDetail": "UP HAULS; LEFT/RIGHT TURN",
  "options.controlScheme.pointerNote": "POINTER & TOUCH STAY ABSOLUTE",
  "options.keyMapping": "CONTROLLER LAYOUT",
  "options.keyMapping.pressKey": "PRESS KEY...",
  "options.keyMapping.rebind": "REBIND",
  "options.keyMapping.clear": "CLEAR",
  "options.keyMapping.defaults": "DEFAULTS",
  "options.keyMapping.rebindHint": "ENTER OR CLICK TO REBIND  DEL CLEARS",
  "options.keyMapping.defaultsRestored": "DEFAULTS RESTORED",
  "options.keyMapping.movedFrom": "MOVED FROM {action}",
  "options.keyMapping.assigned": "{key} ASSIGNED",
  "options.keyMapping.bindingCleared": "BINDING CLEARED",
  "options.keyMapping.bindingCancelled": "BINDING CANCELLED",
  "options.keyMapping.action.steer-left": "STEER LEFT",
  "options.keyMapping.action.steer-right": "STEER RIGHT",
  "options.keyMapping.action.steer-up": "STEER UP",
  "options.keyMapping.action.steer-down": "STEER DOWN",
  "options.keyMapping.action.fire-port": "FIRE PORT",
  "options.keyMapping.action.fire-starboard": "FIRE STARBOARD",
  "options.keyMapping.action.interact": "INTERACT",
  "options.keyMapping.action.captain-menu": "CAPTAIN MENU",
  "options.keyMapping.action.ship-info": "SHIP & LEDGER",
  "options.keyMapping.action.politics": "POLITICS",
  "options.keyMapping.action.screenshot": "SCREENSHOT",
  "options.music": "MUSIC",
  "options.sfx": "SFX",
  "options.mute": "MUTE",
  "options.enterFullscreen": "ENTER FULLSCREEN",
  "options.exitFullscreen": "EXIT FULLSCREEN",
  "options.fullscreenUnavailable": "FULLSCREEN UNAVAILABLE",
  "options.returnToMainMenu": "RETURN TO MAIN MENU",
  "options.quitGame": "QUIT GAME",
  "telemetry.title": "HELP IMPROVE THE GAME?",
  "telemetry.body": "Share anonymous play statistics and crash reports? A random installation ID measures unique players and retention. We do not store names, account IDs, IP addresses, save files, or advertising data. Reports expire after three months. Change this any time in Options.",
  "telemetry.decline": "NO, THANKS",
  "telemetry.accept": "SHARE ANONYMOUS DATA",
  "telemetry.option": "ANONYMOUS DATA",
  "telemetry.on": "ON",
  "telemetry.off": "OFF",
  "start.title": "MARQUE & REPRISAL",
  "start.continue": "CONTINUE",
  "start.loading": "LOADING...",
  "start.newGame": "NEW GAME",
  "start.startGame": "START GAME",
  "start.shipBattle": "SHIP BATTLE",
  "start.historicalBattles": "HISTORICAL BATTLES",
  "battle.choose": "CHOOSE BATTLE",
  "start.pastVoyages": "PAST VOYAGES",
  "start.achievements": "ACHIEVEMENTS",
  "start.credits": "CREDITS",
  "start.saveUnreadable": "SAVE COULD NOT BE READ",
  "start.confirmNewGame": "ARE YOU SURE YOU WANT TO START A NEW GAME?",
  "start.confirmWarning": "THIS WILL END YOUR CURRENT VOYAGE.",
  "common.yes": "YES",
  "common.no": "NO",
  "common.next": "NEXT",
  "common.back": "BACK",
  "common.continue": "CONTINUE",
  "common.decline": "DECLINE",
  "pronoun.objectFemale": "her",
  "pronoun.objectMale": "him",
  "common.close": "CLOSE",
  "common.page": "PAGE",
  "common.days": "DAYS",
  "common.day": "DAY",
  "common.loadingShip": "LOADING SHIP...",
  "common.target": "TARGET",
  "captain.chart": "CAPTAIN'S CHART",
  "captain.shipLedger": "SHIP & LEDGER",
  "captain.politics": "POLITICS",
  "captain.discoveries": "DISCOVERIES",
  "captain.achievements": "ACHIEVEMENTS",
  "captain.aboard": "ABOARD",
  "captain.navigation": "WAYPOINTS",
  "captain.sailingBasics": "SAILING BASICS",
  "captain.tab.map": "MAP",
  "captain.tab.ship": "SHIP",
  "captain.tab.crew": "CREW",
  "captain.tab.politics": "POLITICS",
  "captain.tab.discoveries": "DISCOVERIES",
  "captain.tab.achievements": "ACHIEVEMENTS",
  "captain.tab.navigation": "WAYPOINTS",
  "captain.tab.sailing": "SAILING",
  "captain.tab.options": "OPTIONS",
  "aboard.title": "PEOPLE ABOARD",
  "aboard.captain": "CAPTAIN",
  "aboard.passenger": "PASSENGER",
  "aboard.emissary": "EMISSARY",
  "aboard.colonyLeader": "COLONY LEADER",
  "aboard.crewmate": "CREWMATE",
  "aboard.colonist": "COLONIST",
  "aboard.animal": "ANIMAL",
  "aboard.goal": "GOAL",
  "aboard.skill": "SKILL",
  "ledger.captainAccount": "CAPTAIN'S ACCOUNT",
  "demo.voyageComplete": "DEMO VOYAGE COMPLETE",
  "demo.thanks": "THANKS FOR PLAYING",
  "demo.fullVersion": "BUY THE FULL VERSION ON STEAM FOR MORE",
  "outcome.lostAtSea": "LOST AT SEA",
  "outcome.neverSeenAgain": "WAS NEVER SEEN AGAIN.",
  "outcome.voyageEnded": "VOYAGE ENDED",
  "outcome.cause": "CAUSE",
  "outcome.causeOfDeath": "CAUSE OF DEATH",
  "loadout.title": "CUSTOM LOADOUT",
  "loadout.holdPlan": "HOLD PLAN",
  "navigation.none": "NO ACTIVE WAYPOINTS",
  "navigation.gold": "GOLD",
  "navigation.blue": "BLUE",
  "navigation.gray": "GRAY",
  "navigation.teal": "TEAL",
  "navigation.foundColony": "FOUND THE COLONY",
  "navigation.openTradingPort": "OPEN THE TRADING PORT",
  "navigation.resupplyColony": "RESUPPLY THE COLONY",
  "navigation.diplomaticMission": "DIPLOMATIC MISSION",
  "navigation.passengerMission": "PASSENGER MISSION",
  "navigation.deliveryMission": "DELIVERY MISSION",
  "navigation.activeMission": "ACTIVE MISSION",
  "navigation.explorerLead": "EXPLORER'S LEAD",
  "navigation.whiteWhaleSeen": "WHITE WHALE LAST SEEN",
  "navigation.reportPatron": "REPORT TO YOUR PATRON",
  "navigation.payFamilyDebt": "PAY THE FAMILY DEBT",
  "navigation.returnVictorious": "RETURN HOME VICTORIOUS",
  "navigation.returnHome": "RETURN HOME",
  "navigation.securePermission": "SECURE PERMISSION",
  "navigation.deliverColonyMaterials": "DELIVER COLONY MATERIALS",
  "navigation.deliverLongshipMaterials": "DELIVER LONGSHIP MATERIALS",
  "navigation.deliverWorkshopMaterials": "DELIVER WORKSHOP MATERIALS",
  "navigation.deliverGingerRoots": "DELIVER GINGER ROOTS",
  "quest.journal": "ONGOING QUESTS",
  "quest.none": "NO ONGOING QUESTS",
  "quest.mainVoyage": "MAIN VOYAGE",
  "quest.familyDebtOutstanding": "{amount} OUTSTANDING IN {city}",
  "quest.passenger": "PASSENGER",
  "quest.delivery": "DELIVERY",
  "quest.diplomacy": "DIPLOMACY",
  "quest.mission": "MISSION",
  "quest.colony": "COLONY {city}",
  "quest.longship": "VIKING LONGSHIP",
  "quest.matchlockIndustry": "JAPANESE MATCHLOCKS",
  "quest.caribbeanGinger": "CARIBBEAN GINGER",
  "quest.actionAt": "{city}: {action}",
  "quest.sailTo": "SAIL TO {city}",
  "quest.returnTo": "RETURN TO {city}",
  "quest.acquireFor": "{city}: GET {held}/{quantity} {good}",
  "quest.bringTo": "{city}: BRING {quantity} {good}",
  "quest.returnToEmbark": "RETURN TO {city} TO EMBARK",
  "quest.leaveAndReturn": "LEAVE {city}; RETURN WITH {quantity} {good}",
  "quest.defeatAt": "DEFEAT {count} {enemy} AT {city}",
  "quest.claimAt": "CLAIM THE LONGSHIP AT {city}",
  "quest.buyAt": "BUY THE LONGSHIP AT {city}",
  "quest.fetchReadyDialogue": "That's all the {good} we need to bring to {city}.",
  "ship.vessel": "VESSEL",
  "ship.ledger": "LEDGER",
  "ship.inventory": "INVENTORY",
  "ship.captainLedger": "CAPTAIN'S LEDGER",
  "ship.shipInventory": "SHIP'S INVENTORY",
  "ship.hull": "HULL",
  "ship.armor": "ARMOR",
  "ship.crew": "CREW",
  "ship.propulsion": "PROPULSION",
  "ship.speed": "SPEED",
  "ship.acceleration": "ACCEL",
  "ship.turning": "TURNING",
  "ship.windward": "WINDWARD",
  "ship.seaworthy": "SEAWORTHY",
  "ship.water": "WATER",
  "ship.food": "FOOD",
  "ship.cargoHold": "CARGO HOLD",
  "ship.holdEmpty": "THE HOLD IS EMPTY",
  "ship.itemsDocuments": "ITEMS & DOCUMENTS",
  "ship.inventoryEmpty": "INVENTORY IS EMPTY",
  "ship.realizedPnl": "REALIZED P/L",
  "ship.cash": "CASH",
  "ship.date": "DATE",
  "ship.port": "PORT",
  "ship.entry": "ENTRY",
  "ship.amount": "AMOUNT",
  "ship.balance": "BAL",
  "ship.pnl": "P/L",
  "ship.type": "TYPE",
  "ship.detail": "DETAIL",
  "ship.manifest": "MANIFEST",
  "ship.held": "HELD",
  "ship.average": "AVG",
  "ship.doubloons": "DOUBLOONS",
  "ship.armament": "ARMAMENT",
  "ship.current": "CURRENT",
  "ship.new": "NEW",
  "ship.prize": "PRIZE",
  "ship.guns": "GUNS",
  "ship.atWill": "AT WILL",
  "ship.oarNoDeadZone": "OAR / NO DEAD ZONE",
  "ship.oarSailAdaptive": "OAR + SAIL / ROW TO BOOST",
  "ship.item": "ITEM",
  "ship.equipment": "EQUIPMENT",
  "ship.delivery": "DELIVERY",
  "ship.passenger": "PASSENGER",
  "ship.openingBalance": "OPENING BALANCE",
  "ship.aboard": "ABOARD",
  "ship.shipyardNew": "SHIPYARD / NEW VESSEL",
  "ship.surrenderedPrize": "SURRENDERED PRIZE",
  "discoveries.title": "DISCOVERIES",
  "discoveries.found": "FOUND",
  "discoveries.globeMapped": "GLOBE MAPPED",
  "discoveries.none": "NO DISCOVERIES YET",
  "politics.title": "POLITICS",
  "politics.ally": "ALLY",
  "politics.friendly": "FRIENDLY",
  "politics.war": "WAR",
  "politics.neutral": "NEUTRAL",
  "politics.noContact": "NO CONTACT",
  "politics.stanceToward": "STANCE TOWARD",
  "politics.playerStanding": "YOU / TRADE",
  "politics.power": "POWER",
  "politics.status": "STATUS",
  "politics.you": "YOU",
  "politics.latest": "LATEST",
  "politics.recent": "RECENT DEVELOPMENTS",
  "politics.marque": "MARQUE",
  "politics.legendAlly": "A ALLY",
  "politics.legendWar": "W WAR",
  "politics.legendNeutral": "- NEUTRAL  . NO CONTACT",
  "politics.legendSuzerainty": "VASSAL >  TRIBUTE ~  UNION =",
  "politics.legendTrade": "% DUTY  X CLOSED  P PASS  O OPEN  M MARQUE",
  "politics.legendCompact": "- NEUT  . NONE",
  "politics.allPowers": "ALL POWERS",
  "politics.vassalOf": "VASSAL OF",
  "politics.suzerainOf": "SUZERAIN OF",
  "politics.tributaryTo": "TRIBUTARY TO",
  "politics.tributeFrom": "TRIBUTE FROM",
  "politics.unionWith": "UNION WITH",
  "politics.hostile": "HOSTILE",
  "politics.angry": "ANGRY",
  "politics.cold": "COLD",
  "politics.warm": "WARM",
  "politics.favored": "FAVORED",
  "politics.trusted": "TRUSTED",
  "faction.pirate": "PIRATE",
  "faction.england": "ENGLISH",
  "faction.scotland": "SCOTTISH",
  "faction.france": "FRENCH",
  "faction.spain": "SPANISH",
  "faction.portugal": "PORTUGUESE",
  "faction.habsburg": "HABSBURG",
  "faction.hungary": "HUNGARIAN",
  "faction.ottoman": "OTTOMAN",
  "faction.venice": "VENETIAN",
  "faction.genoa": "GENOESE",
  "faction.papalStates": "PAPAL",
  "faction.hospitallers": "HOSPITALLER",
  "faction.ming": "MING",
  "faction.inca": "INCA",
  "faction.safavid": "SAFAVID",
  "faction.muscovy": "MUSCOVITE",
  "faction.polandLithuania": "POLISH-LITHUANIAN",
  "faction.sweden": "SWEDISH",
  "faction.denmarkNorway": "DANO-NORWEGIAN",
  "faction.songhai": "SONGHAI",
  "faction.morocco": "MOROCCAN",
  "faction.ethiopia": "ETHIOPIAN",
  "faction.vijayanagara": "VIJAYANAGARAN",
  "faction.gujarat": "GUJARATI",
  "faction.bengal": "BENGALI",
  "faction.delhi": "DELHI",
  "faction.ayutthaya": "AYUTTHAYAN",
  "faction.japan": "JAPANESE",
  "faction.joseon": "JOSEON",
  "good.hardtack": "Hardtack",
  "good.freshWater": "Fresh Water",
  "good.foragedFood": "Foraged Food",
  "good.grain": "Grain",
  "good.fish": "Fish",
  "good.whaleBlubber": "Whale Blubber",
  "good.beaverPelts": "Beaver Pelts",
  "good.cheese": "Cheese",
  "good.wine": "Wine",
  "good.oliveOil": "Olive Oil",
  "good.salt": "Salt",
  "good.sugar": "Sugar",
  "good.timber": "Timber",
  "good.coal": "Coal",
  "good.wool": "Wool",
  "good.cotton": "Cotton",
  "good.flax": "Flax",
  "good.iron": "Iron",
  "good.copper": "Copper",
  "good.tin": "Tin",
  "good.amber": "Amber",
  "good.furs": "Furs",
  "good.beeswax": "Beeswax",
  "good.navalStores": "Naval Stores",
  "good.sulfur": "Sulfur",
  "good.arms": "Pikes & Blades",
  "good.gunpowder": "Gunpowder",
  "good.matchlocks": "Matchlocks",
  "good.linenCloth": "Linen Cloth",
  "good.woolCloth": "Wool Cloth",
  "good.cottonCloth": "Cotton Cloth",
  "good.paper": "Paper",
  "good.printedBooks": "Printed Books",
  "good.silk": "Silk",
  "good.silkCloth": "Silk Cloth",
  "good.lacquerware": "Lacquerware",
  "good.ginseng": "Ginseng",
  "good.pepper": "Pepper",
  "good.cinnamon": "Cinnamon",
  "good.cloves": "Cloves",
  "good.nutmeg": "Nutmeg",
  "good.ginger": "Ginger",
  "good.tea": "Tea",
  "good.coffee": "Coffee",
  "good.cacao": "Cacao",
  "good.dyes": "Dyes",
  "good.indigo": "Indigo",
  "good.porcelain": "Porcelain",
  "good.glassware": "Glassware",
  "good.carpets": "Carpets",
  "good.artwork": "Artwork",
  "good.perfume": "Perfume",
  "good.ivory": "Ivory",
  "good.silver": "Silver",
  "good.gold": "Gold",
  "voyages.title": "PAST VOYAGES",
  "voyages.register": "CAPTAINS' REGISTER",
  "voyages.voyages": "VOYAGES",
  "voyages.totalDays": "TOTAL DAYS",
  "voyages.longest": "LONGEST VOYAGE",
  "voyages.totalEarned": "TOTAL EARNED",
  "voyages.mostEarned": "MOST EARNED",
  "voyages.richestEnding": "RICHEST ENDING",
  "voyages.mostDiscoveries": "MOST DISCOVERIES",
  "voyages.winDeathQuitDemo": "WIN / DEATH / QUIT / DEMO",
  "voyages.none": "NO PAST VOYAGES YET",
  "voyages.home": "HOME",
  "voyages.resultGoal": "RESULT / GOAL",
  "voyages.lastVessel": "LAST VESSEL",
  "voyages.daysMapped": "DAYS / WORLD MAPPED",
  "voyages.earnedNet": "EARNED / NET",
  "voyages.finalTradePnl": "FINAL / TRADE PNL",
  "voyages.discoveryPortsWorld": "DISC / PORTS / WORLD",
  "voyages.questsMarques": "QUESTS / MARQUES",
  "voyages.crewLostPiracy": "CREW LOST / PIRACY",
  "voyages.fate": "FATE",
  "intro.papers": "CAPTAIN'S PAPERS",
  "intro.homePort": "HOME PORT",
  "intro.nationality": "NATIONALITY",
  "intro.religion": "RELIGION",
  "intro.born": "BORN",
  "intro.age": "AGE",
  "intro.sex": "SEX",
  "intro.male": "MALE",
  "intro.female": "FEMALE",
  "intro.begin": "BEGIN VOYAGE",
  "tutorial.turnSail": "TURN AND SAIL",
  "tutorial.upwind": "SAILING UPWIND",
  "tutorial.rowing": "ROWING",
  "tutorial.escapeShore": "ESCAPE THE SHORE",
  "tutorial.takeHelm": "TAKE THE HELM",
  "tutorial.pressHold": "PRESS + HOLD",
  "tutorial.tiltHold": "TILT + HOLD",
  "tutorial.touchHold": "TOUCH + HOLD",
  "tutorial.clickHold": "CLICK + HOLD",
  "tutorial.turnBow": "TURN THE BOW",
  "tutorial.wind": "WIND",
  "tutorial.tack": "TACK",
  "tutorial.holdRow": "HOLD TO ROW",
  "tutorial.releaseRest": "RELEASE = REST",
  "tutorial.haul": "HAUL",
  "tutorial.openWater": "OPEN WATER",
  "tutorial.touchSteer": "Touch and hold anywhere around your ship. The bow turns toward your finger. Keep holding while it sails.",
  "tutorial.mouseSteer": "Click and hold anywhere around your ship. The bow turns toward the pointer. Keep holding while it sails.",
  "tutorial.keyboardSteer": "Press and hold WASD or an arrow key. The bow turns toward that direction. Keep holding while it sails.",
  "tutorial.controllerSteer": "Tilt and hold the left stick. The bow turns toward that direction. Keep holding while it sails.",
  "tutorial.tacking": "Most sailing ships cannot point straight into the wind. Aim to either side, then cross back and forth. This zigzag is called tacking.",
  "tutorial.touchRow": "On an oared ship, hold ahead to row or behind to reverse. Hold to either side while stopped to turn in place. Release to rest; more rowers are stronger but eat more.",
  "tutorial.mouseRow": "On an oared ship, hold ahead to row or behind to reverse. Hold to either side while stopped to turn in place. Release to rest; more rowers are stronger but eat more.",
  "tutorial.keyboardRowAbsolute": "On an oared ship, hold toward the bow to row, behind it to reverse, or to either side while stopped to turn in place. Release to rest; more rowers are stronger but eat more.",
  "tutorial.keyboardRowRelative": "On an oared ship, hold forward to row, back to reverse, or left/right while stopped to turn in place. Release to rest; more rowers are stronger but eat more.",
  "tutorial.controllerRowAbsolute": "On an oared ship, hold the left stick toward the bow to row, behind it to reverse, or to either side while stopped to turn in place. Release to rest; more rowers are stronger but eat more.",
  "tutorial.controllerRowRelative": "On an oared ship, hold the left stick forward to row, back to reverse, or left/right while stopped to turn in place. Release to rest; more rowers are stronger but eat more.",
  "tutorial.touchHaul": "If wind pins you against a riverbank or coast, steer toward open water. Your crew immediately begins to haul along the shore, very slowly.",
  "tutorial.mouseHaul": "If wind pins you against a riverbank or coast, steer toward open water. Your crew immediately begins to haul along the shore, very slowly.",
  "tutorial.keyboardHaul": "If wind pins you against a riverbank or coast, steer toward open water. Your crew immediately begins to haul along the shore, very slowly.",
  "tutorial.controllerHaul": "If wind pins you against a riverbank or coast, steer toward open water. Your crew immediately begins to haul along the shore, very slowly.",
  "dialogue.leavePort": "LEAVE PORT",
  "dialogue.buy": "BUY",
  "dialogue.sell": "SELL",
  "dialogue.trade": "TRADE",
  "dialogue.accept": "ACCEPT",
  "dialogue.capital": "CAPITAL",
  "status.mapped": "MAPPED",
  "status.drinkableWaterLow": "DRINKABLE WATER LOW",
  "status.sunset": "SUNSET",
  "status.sunrise": "SUNRISE",
  "storm.manOverboardLabel": "MAN OVERBOARD",
  "storm.manOverboardFirst": "Hard over! A breaking sea has swept crew overboard. Bring us alongside before the sea takes them.",
  "storm.manOverboardNoticeOne": "MAN OVERBOARD",
  "storm.manOverboardNoticeMany": "{count} CREW OVERBOARD",
  "storm.manOverboardRecoveredOne": "CREWMATE RECOVERED",
  "storm.manOverboardRecoveredMany": "{count} CREW RECOVERED",
  "storm.manOverboardDrownedOne": "A CREWMATE WAS LOST",
  "storm.manOverboardDrownedMany": "{count} CREW LOST OVERBOARD",
  "hud.tooltip.localDate": "Local date: {date}",
  "hud.tooltip.doubloons": "{count} doubloons",
  "hud.tooltip.hull": "Hull strength: {current}/{maximum}",
  "hud.tooltip.waterDaysOne": "{days} day of drinkable water remains",
  "hud.tooltip.waterDaysMany": "{days} days of drinkable water remain",
  "hud.tooltip.foodDaysOne": "{days} day of food remains",
  "hud.tooltip.foodDaysMany": "{days} days of food remain",
  "hud.tooltip.crewCountOne": "{count} crew member",
  "hud.tooltip.crewCountMany": "{count} crew",
  "hud.tooltip.passengerCountOne": "{count} passenger",
  "hud.tooltip.passengerCountMany": "{count} passengers",
  "hud.tooltip.aboardCrew": "{crew} aboard",
  "hud.tooltip.aboardCrewPassengers": "{crew} + {passengers} aboard",
  "hud.tooltip.animalCompanion.panda": "1 panda",
  "hud.tooltip.animalCompanion.penguin": "1 penguin",
  "hud.tooltip.animalCompanion.raccoon": "1 raccoon",
  "hud.tooltip.aboardCrewAnimals": "{crew} + {animals} aboard",
  "hud.tooltip.aboardCrewPassengersAnimals": "{crew} + {passengers} + {animals} aboard",
  "discovery.greatBarrierReef.name": "Great Barrier Reef",
  "discovery.greatBarrierReef.notice": "You have discovered the Great Barrier Reef",
  "discovery.greatBarrierReef.detail": "Coral Sea, northeast Australia",
  "discovery.greatBarrierReef.captain": "The sea is alive beneath us—coral gardens stretching farther than the eye can follow!",
  "discovery.greatBarrierReef.reportCaptain": "For days the sea off Australia changed color beneath us. Coral gardens stretched beyond sight, alive with fish, yet hidden just below the surface.",
  "discovery.greatBarrierReef.reportPatron": "A living rampart longer than any wall built by kings. Mark every passage carefully; a wonder beneath the sea is also a navigator's peril.",
  "status.loading": "Loading Marque & Reprisal...",
  "aria.worldMap": "world map",
  "aria.shipBattleLake": "ship battle lake",
  "aria.historicalBattle": "historical sea battle",
  "aria.canvas": "Marque & Reprisal {surface}, {width} by {height}"
});

const CHINESE_SIMPLIFIED = Object.freeze({
  "language.english": "英文",
  "language.chineseSimplified": "简体中文",
  "language.russian": "俄语",
  "language.spanish": "西班牙语",
  "language.portugueseBrazil": "巴西葡萄牙语",
  "language.japanese": "日语",
  "language.german": "德语",
  "language.french": "法语",
  "language.polish": "波兰语",
  "language.chineseTraditional": "繁体中文",
  "language.korean": "韩语",
  "options.title": "选项",
  "options.language": "语言",
  "options.controllerIcons": "控制器图标",
  "options.controllerIcons.automatic": "自动",
  "options.controllerIcons.xbox": "XBOX",
  "options.controllerIcons.playstation": "PS",
  "options.controllerIcons.nintendo": "任天堂",
  "options.controllerIcons.generic": "通用",
  "options.controlScheme": "操控方式",
  "options.controlScheme.title": "操舵方式",
  "options.controlScheme.absolute": "绝对",
  "options.controlScheme.relative": "相对",
  "options.controlScheme.absoluteDetail": "方向键指定船头方向",
  "options.controlScheme.relativeDetail": "向前拖船，左右键转向",
  "options.controlScheme.pointerNote": "指针与触控始终使用绝对操控",
  "options.keyMapping": "控制器布局",
  "options.keyMapping.pressKey": "请按键……",
  "options.keyMapping.rebind": "重设按键",
  "options.keyMapping.clear": "清除",
  "options.keyMapping.defaults": "默认",
  "options.keyMapping.rebindHint": "按回车或点击重设　DEL 清除",
  "options.keyMapping.defaultsRestored": "已恢复默认设置",
  "options.keyMapping.movedFrom": "已从{action}移除",
  "options.keyMapping.assigned": "已绑定 {key}",
  "options.keyMapping.bindingCleared": "绑定已清除",
  "options.keyMapping.bindingCancelled": "已取消绑定",
  "options.keyMapping.action.steer-left": "向左转向",
  "options.keyMapping.action.steer-right": "向右转向",
  "options.keyMapping.action.steer-up": "向上转向",
  "options.keyMapping.action.steer-down": "向下转向",
  "options.keyMapping.action.fire-port": "左舷开火",
  "options.keyMapping.action.fire-starboard": "右舷开火",
  "options.keyMapping.action.interact": "互动",
  "options.keyMapping.action.captain-menu": "船长菜单",
  "options.keyMapping.action.ship-info": "船只与账簿",
  "options.keyMapping.action.politics": "政治",
  "options.keyMapping.action.screenshot": "截图",
  "options.music": "音乐",
  "options.sfx": "音效",
  "options.mute": "静音",
  "options.enterFullscreen": "进入全屏",
  "options.exitFullscreen": "退出全屏",
  "options.fullscreenUnavailable": "无法使用全屏",
  "options.returnToMainMenu": "返回主菜单",
  "options.quitGame": "退出游戏",
  "telemetry.title": "帮助改进游戏？",
  "telemetry.body": "是否分享匿名游玩统计和崩溃报告？随机安装编号用于统计玩家数量和留存率。我们不会存储姓名、账户编号、IP 地址、存档或广告数据。报告会在三个月后删除。可随时在选项中更改。",
  "telemetry.decline": "不用，谢谢",
  "telemetry.accept": "分享匿名数据",
  "telemetry.option": "匿名数据",
  "telemetry.on": "开启",
  "telemetry.off": "关闭",
  "start.title": "私掠与报复",
  "start.continue": "继续航行",
  "start.loading": "读取中……",
  "start.newGame": "新游戏",
  "start.startGame": "开始游戏",
  "start.shipBattle": "海战",
  "start.historicalBattles": "历史战役",
  "battle.choose": "选择战役",
  "start.pastVoyages": "往昔航程",
  "start.achievements": "成就",
  "start.credits": "制作人员",
  "start.saveUnreadable": "无法读取存档",
  "start.confirmNewGame": "确定要开始新游戏吗？",
  "start.confirmWarning": "当前航程将会结束。",
  "common.yes": "是",
  "common.no": "否",
  "common.next": "下一页",
  "common.back": "返回",
  "common.continue": "继续",
  "common.decline": "婉拒",
  "pronoun.objectFemale": "她",
  "pronoun.objectMale": "他",
  "common.close": "关闭",
  "common.page": "页",
  "common.days": "天",
  "common.day": "天",
  "common.loadingShip": "船只读取中……",
  "common.target": "目标",
  "captain.chart": "船长海图",
  "captain.shipLedger": "船只与账簿",
  "captain.politics": "列国政局",
  "captain.discoveries": "发现记录",
  "captain.achievements": "成就",
  "captain.aboard": "船上人员",
  "captain.navigation": "航路点",
  "captain.sailingBasics": "航海入门",
  "captain.tab.map": "海图",
  "captain.tab.ship": "船只",
  "captain.tab.crew": "船员",
  "captain.tab.politics": "政局",
  "captain.tab.discoveries": "发现",
  "captain.tab.achievements": "成就",
  "captain.tab.navigation": "航路点",
  "captain.tab.sailing": "航海",
  "captain.tab.options": "选项",
  "aboard.title": "船上人员",
  "aboard.captain": "船长",
  "aboard.passenger": "乘客",
  "aboard.emissary": "使节",
  "aboard.colonyLeader": "殖民领队",
  "aboard.crewmate": "船员",
  "aboard.colonist": "殖民者",
  "aboard.animal": "动物",
  "aboard.goal": "目标",
  "aboard.skill": "技能",
  "ledger.captainAccount": "船长记录",
  "demo.voyageComplete": "试玩航程结束",
  "demo.thanks": "感谢游玩",
  "demo.fullVersion": "在 STEAM 购买完整版继续航行",
  "outcome.lostAtSea": "葬身海上",
  "outcome.neverSeenAgain": "从此杳无音信。",
  "outcome.voyageEnded": "航程结束",
  "outcome.cause": "死因",
  "outcome.causeOfDeath": "死亡原因",
  "loadout.title": "自定义配载",
  "loadout.holdPlan": "货舱规划",
  "navigation.none": "目前没有航路点",
  "navigation.gold": "金色",
  "navigation.blue": "蓝色",
  "navigation.gray": "灰色",
  "navigation.teal": "青色",
  "navigation.foundColony": "建立殖民地",
  "navigation.openTradingPort": "开放贸易港",
  "navigation.resupplyColony": "补给殖民地",
  "navigation.diplomaticMission": "外交任务",
  "navigation.passengerMission": "载客任务",
  "navigation.deliveryMission": "递送任务",
  "navigation.activeMission": "当前任务",
  "navigation.explorerLead": "探险线索",
  "navigation.whiteWhaleSeen": "白鲸最后目击地",
  "navigation.reportPatron": "向赞助人报告",
  "navigation.payFamilyDebt": "偿还家族债务",
  "navigation.returnVictorious": "凯旋归乡",
  "navigation.returnHome": "返回故乡",
  "navigation.securePermission": "取得许可",
  "navigation.deliverColonyMaterials": "交付殖民物资",
  "navigation.deliverLongshipMaterials": "交付长船材料",
  "navigation.deliverWorkshopMaterials": "交付工坊材料",
  "navigation.deliverGingerRoots": "交付姜种",
  "quest.journal": "进行中的任务",
  "quest.none": "没有进行中的任务",
  "quest.mainVoyage": "主要航程",
  "quest.familyDebtOutstanding": "{city}尚欠{amount}",
  "quest.passenger": "乘客",
  "quest.delivery": "递送",
  "quest.diplomacy": "外交",
  "quest.mission": "任务",
  "quest.colony": "殖民地 {city}",
  "quest.longship": "维京长船",
  "quest.matchlockIndustry": "日本火绳枪",
  "quest.caribbeanGinger": "加勒比姜种植",
  "quest.actionAt": "{city}：{action}",
  "quest.sailTo": "驶往{city}",
  "quest.returnTo": "返回{city}",
  "quest.acquireFor": "为{city}取得{good} {held}/{quantity}",
  "quest.bringTo": "把{quantity}份{good}带到{city}",
  "quest.returnToEmbark": "返回{city}让远征队登船",
  "quest.leaveAndReturn": "离开{city}；带{quantity}份{good}返回",
  "quest.defeatAt": "在{city}击败{count}艘{enemy}船",
  "quest.claimAt": "在{city}领取长船",
  "quest.buyAt": "在{city}购买长船",
  "quest.fetchReadyDialogue": "我们带到{city}所需的{good}已经齐了。",
  "ship.vessel": "船只",
  "ship.ledger": "账簿",
  "ship.inventory": "物品",
  "ship.captainLedger": "船长账簿",
  "ship.shipInventory": "船上物品",
  "ship.hull": "船体",
  "ship.armor": "装甲",
  "ship.crew": "船员",
  "ship.propulsion": "动力",
  "ship.speed": "速度",
  "ship.acceleration": "加速",
  "ship.turning": "转向",
  "ship.windward": "迎风",
  "ship.seaworthy": "适航",
  "ship.water": "淡水",
  "ship.food": "食物",
  "ship.cargoHold": "货舱",
  "ship.holdEmpty": "货舱为空",
  "ship.itemsDocuments": "物品与文书",
  "ship.inventoryEmpty": "没有物品",
  "ship.realizedPnl": "已结盈亏",
  "ship.cash": "现款",
  "ship.date": "日期",
  "ship.port": "港口",
  "ship.entry": "事项",
  "ship.amount": "金额",
  "ship.balance": "余额",
  "ship.pnl": "盈亏",
  "ship.type": "类型",
  "ship.detail": "详情",
  "ship.manifest": "货单",
  "ship.held": "持有",
  "ship.average": "均价",
  "ship.doubloons": "达布隆",
  "ship.armament": "武装",
  "ship.current": "现有",
  "ship.new": "新船",
  "ship.prize": "战利船",
  "ship.guns": "火炮",
  "ship.atWill": "随时可用",
  "ship.oarNoDeadZone": "船桨／无迎风死区",
  "ship.oarSailAdaptive": "桨帆并用／划桨加速",
  "ship.item": "物品",
  "ship.equipment": "装备",
  "ship.delivery": "递送",
  "ship.passenger": "乘客",
  "ship.openingBalance": "期初余额",
  "ship.aboard": "船上",
  "ship.shipyardNew": "船厂／新船",
  "ship.surrenderedPrize": "受降战利船",
  "discoveries.title": "发现记录",
  "discoveries.found": "已发现",
  "discoveries.globeMapped": "世界测绘",
  "discoveries.none": "尚无发现",
  "politics.title": "列国政局",
  "politics.ally": "同盟",
  "politics.friendly": "友好",
  "politics.war": "战争",
  "politics.neutral": "中立",
  "politics.noContact": "未接触",
  "politics.stanceToward": "各国立场",
  "politics.playerStanding": "对你／贸易",
  "politics.power": "势力",
  "politics.status": "关系",
  "politics.you": "你",
  "politics.latest": "最新",
  "politics.recent": "近期政局",
  "politics.marque": "私掠许可",
  "politics.legendAlly": "A 同盟",
  "politics.legendWar": "W 战争",
  "politics.legendNeutral": "- 中立  . 未接触",
  "politics.legendSuzerainty": "藩属 >  朝贡 ~  共主邦联 =",
  "politics.legendTrade": "% 关税  X 封闭  P 许可  O 开放  M 私掠",
  "politics.legendCompact": "- 中立  . 未知",
  "politics.allPowers": "所有势力",
  "politics.vassalOf": "臣属于",
  "politics.suzerainOf": "宗主于",
  "politics.tributaryTo": "朝贡于",
  "politics.tributeFrom": "受朝贡",
  "politics.unionWith": "共主联合",
  "politics.hostile": "敌视",
  "politics.angry": "愤怒",
  "politics.cold": "冷淡",
  "politics.warm": "友善",
  "politics.favored": "器重",
  "politics.trusted": "信任",
  "faction.pirate": "海盗",
  "faction.england": "英格兰",
  "faction.scotland": "苏格兰",
  "faction.france": "法兰西",
  "faction.spain": "西班牙",
  "faction.portugal": "葡萄牙",
  "faction.habsburg": "哈布斯堡",
  "faction.hungary": "匈牙利",
  "faction.ottoman": "奥斯曼",
  "faction.venice": "威尼斯",
  "faction.genoa": "热那亚",
  "faction.papalStates": "教宗国",
  "faction.hospitallers": "医院骑士团",
  "faction.ming": "明朝",
  "faction.inca": "印加",
  "faction.safavid": "萨法维",
  "faction.muscovy": "莫斯科公国",
  "faction.polandLithuania": "波兰-立陶宛",
  "faction.sweden": "瑞典",
  "faction.denmarkNorway": "丹麦-挪威",
  "faction.songhai": "桑海",
  "faction.morocco": "摩洛哥",
  "faction.ethiopia": "埃塞俄比亚",
  "faction.vijayanagara": "毗奢耶那伽罗",
  "faction.gujarat": "古吉拉特",
  "faction.bengal": "孟加拉",
  "faction.delhi": "德里",
  "faction.ayutthaya": "阿瑜陀耶",
  "faction.japan": "日本",
  "faction.joseon": "朝鲜",
  "good.hardtack": "硬饼干",
  "good.freshWater": "淡水",
  "good.foragedFood": "采集食物",
  "good.grain": "谷物",
  "good.fish": "鱼",
  "good.whaleBlubber": "鲸脂",
  "good.beaverPelts": "海狸皮",
  "good.cheese": "奶酪",
  "good.wine": "葡萄酒",
  "good.oliveOil": "橄榄油",
  "good.salt": "盐",
  "good.sugar": "糖",
  "good.timber": "木材",
  "good.coal": "煤炭",
  "good.wool": "羊毛",
  "good.cotton": "棉花",
  "good.flax": "亚麻",
  "good.iron": "铁",
  "good.copper": "铜",
  "good.tin": "锡",
  "good.amber": "琥珀",
  "good.furs": "毛皮",
  "good.beeswax": "蜂蜡",
  "good.navalStores": "船用物资",
  "good.sulfur": "硫磺",
  "good.arms": "長矛與刀劍",
  "good.gunpowder": "火药",
  "good.matchlocks": "火绳枪",
  "good.linenCloth": "亚麻布",
  "good.woolCloth": "呢绒",
  "good.cottonCloth": "棉布",
  "good.paper": "纸张",
  "good.printedBooks": "印刷书籍",
  "good.silk": "生丝",
  "good.silkCloth": "丝绸",
  "good.lacquerware": "漆器",
  "good.ginseng": "人参",
  "good.pepper": "胡椒",
  "good.cinnamon": "肉桂",
  "good.cloves": "丁香",
  "good.nutmeg": "肉豆蔻",
  "good.ginger": "姜",
  "good.tea": "茶叶",
  "good.coffee": "咖啡",
  "good.cacao": "可可",
  "good.dyes": "染料",
  "good.indigo": "靛青",
  "good.porcelain": "瓷器",
  "good.glassware": "玻璃器皿",
  "good.carpets": "地毯",
  "good.artwork": "艺术品",
  "good.perfume": "香水",
  "good.ivory": "象牙",
  "good.silver": "白银",
  "good.gold": "黄金",
  "voyages.title": "往昔航程",
  "voyages.register": "历任船长名录",
  "voyages.voyages": "航程次数",
  "voyages.totalDays": "累计天数",
  "voyages.longest": "最长航程",
  "voyages.totalEarned": "总收入",
  "voyages.mostEarned": "单程最高收入",
  "voyages.richestEnding": "最高结余",
  "voyages.mostDiscoveries": "单程最多发现",
  "voyages.winDeathQuitDemo": "胜利／死亡／退出／试玩",
  "voyages.none": "尚无往昔航程",
  "voyages.home": "故乡",
  "voyages.resultGoal": "结局／目标",
  "voyages.lastVessel": "最后船只",
  "voyages.daysMapped": "天数／世界测绘",
  "voyages.earnedNet": "收入／净额",
  "voyages.finalTradePnl": "结余／贸易盈亏",
  "voyages.discoveryPortsWorld": "发现／港口／环球",
  "voyages.questsMarques": "任务／私掠许可",
  "voyages.crewLostPiracy": "阵亡船员／海盗行为",
  "voyages.fate": "结局",
  "intro.papers": "船长文书",
  "intro.homePort": "故乡港口",
  "intro.nationality": "国籍",
  "intro.religion": "宗教",
  "intro.born": "出生",
  "intro.age": "年龄",
  "intro.sex": "性别",
  "intro.male": "男",
  "intro.female": "女",
  "intro.begin": "扬帆启程",
  "tutorial.turnSail": "转向与航行",
  "tutorial.upwind": "逆风航行",
  "tutorial.rowing": "划桨",
  "tutorial.escapeShore": "脱离岸边",
  "tutorial.takeHelm": "接掌船舵",
  "tutorial.pressHold": "按住按键",
  "tutorial.tiltHold": "推住摇杆",
  "tutorial.touchHold": "触摸并按住",
  "tutorial.clickHold": "点击并按住",
  "tutorial.turnBow": "转动船头",
  "tutorial.wind": "风向",
  "tutorial.tack": "抢风",
  "tutorial.holdRow": "按住划桨",
  "tutorial.releaseRest": "松开休息",
  "tutorial.haul": "拖船",
  "tutorial.openWater": "开阔水面",
  "tutorial.touchSteer": "触摸并按住船只周围。船头会转向手指。航行时请继续按住。",
  "tutorial.mouseSteer": "点击并按住船只周围。船头会转向指针。航行时请继续按住。",
  "tutorial.keyboardSteer": "按住WASD或方向键。船头会转向该方向。航行时请继续按住。",
  "tutorial.controllerSteer": "倾斜并按住左摇杆。船头会转向该方向。航行时请继续按住。",
  "tutorial.tacking": "多数帆船无法直迎风向。先驶向风的一侧，再来回穿越风向。这种之字航法叫作抢风航行。",
  "tutorial.touchRow": "在有桨的船上，触摸并按住一个方向即可朝该方向划行。松开后桨手休息。更多船员会让桨力更强，但划桨会更快消耗食物。",
  "tutorial.mouseRow": "在有桨的船上，点击并按住一个方向即可朝该方向划行。松开后桨手休息。更多船员会让桨力更强，但划桨会更快消耗食物。",
  "tutorial.keyboardRowAbsolute": "在有桨的船上，按住方向键即可朝该方向划行。松开后桨手休息。更多船员会让桨力更强，但划桨会更快消耗食物。",
  "tutorial.keyboardRowRelative": "在有桨的船上，按住前进键即可划行。松开后桨手休息。更多船员会让桨力更强，但划桨会更快消耗食物。",
  "tutorial.controllerRowAbsolute": "在有桨的船上，将左摇杆推向一个方向并按住即可朝该方向划行。松开后桨手休息。更多船员会让桨力更强，但划桨会更快消耗食物。",
  "tutorial.controllerRowRelative": "在有桨的船上，向前推住左摇杆即可划行。松开后桨手休息。更多船员会让桨力更强，但划桨会更快消耗食物。",
  "tutorial.touchHaul": "若风把船困在河岸或海岸，朝开阔水面触摸并按住。船员会沿岸缓慢拖船。",
  "tutorial.mouseHaul": "若风把船困在河岸或海岸，朝开阔水面点击并按住。船员会沿岸缓慢拖船。",
  "tutorial.keyboardHaul": "若风把船困在河岸或海岸，按住朝开阔水面的方向键。船员会沿岸缓慢拖船。",
  "tutorial.controllerHaul": "若风把船困在河岸或海岸，朝开阔水面按住左摇杆。船员会沿岸缓慢拖船。",
  "dialogue.leavePort": "离开港口",
  "dialogue.buy": "购买",
  "dialogue.sell": "出售",
  "dialogue.trade": "贸易",
  "dialogue.accept": "接受",
  "dialogue.capital": "首都",
  "status.mapped": "已测绘",
  "status.drinkableWaterLow": "饮用水不足",
  "status.sunset": "日落",
  "status.sunrise": "日出",
  "storm.manOverboardLabel": "有人落水",
  "storm.manOverboardFirst": "快转舵！巨浪把船员卷下海了。快靠过去，别让大海吞没他们。",
  "storm.manOverboardNoticeOne": "有人落水",
  "storm.manOverboardNoticeMany": "{count}名船员落水",
  "storm.manOverboardRecoveredOne": "救回一名船员",
  "storm.manOverboardRecoveredMany": "救回{count}名船员",
  "storm.manOverboardDrownedOne": "一名船员葬身海中",
  "storm.manOverboardDrownedMany": "{count}名船员葬身海中",
  "hud.tooltip.localDate": "当地日期：{date}",
  "hud.tooltip.doubloons": "达布隆：{count}",
  "hud.tooltip.hull": "船体强度：{current}/{maximum}",
  "hud.tooltip.waterDaysOne": "饮用水还可维持{days}天",
  "hud.tooltip.waterDaysMany": "饮用水还可维持{days}天",
  "hud.tooltip.foodDaysOne": "食物还可维持{days}天",
  "hud.tooltip.foodDaysMany": "食物还可维持{days}天",
  "hud.tooltip.crewCountOne": "{count}名船员",
  "hud.tooltip.crewCountMany": "{count}名船员",
  "hud.tooltip.passengerCountOne": "{count}名乘客",
  "hud.tooltip.passengerCountMany": "{count}名乘客",
  "hud.tooltip.aboardCrew": "船上有{crew}",
  "hud.tooltip.aboardCrewPassengers": "船上有{crew}＋{passengers}",
  "hud.tooltip.animalCompanion.panda": "1只熊猫",
  "hud.tooltip.animalCompanion.penguin": "1只企鹅",
  "hud.tooltip.animalCompanion.raccoon": "1只浣熊",
  "hud.tooltip.aboardCrewAnimals": "船上有{crew}＋{animals}",
  "hud.tooltip.aboardCrewPassengersAnimals": "船上有{crew}＋{passengers}＋{animals}",
  "discovery.greatBarrierReef.name": "大堡礁",
  "discovery.greatBarrierReef.notice": "你发现了大堡礁",
  "discovery.greatBarrierReef.detail": "澳大利亚东北部，珊瑚海",
  "discovery.greatBarrierReef.captain": "我们脚下的海洋生机盎然——珊瑚花园一直延伸到视野尽头！",
  "discovery.greatBarrierReef.reportCaptain": "在澳大利亚近海航行的几天里，我们脚下的海水不断变换颜色。看不见尽头的珊瑚花园藏在水面之下，鱼群穿梭其中。",
  "discovery.greatBarrierReef.reportPatron": "一道比任何帝王筑起的城墙都更长的活屏障。仔细标出每条水道；海下的奇观同样是航海者的险境。",
  "status.loading": "《Marque & Reprisal》读取中……",
  "aria.worldMap": "世界地图",
  "aria.shipBattleLake": "海战水域",
  "aria.historicalBattle": "历史海战",
  "aria.canvas": "Marque & Reprisal {surface}，{width}乘{height}"
});

const JAPANESE = Object.freeze({
  "language.english": "英語",
  "language.chineseSimplified": "簡体字中国語",
  "language.russian": "ロシア語",
  "language.spanish": "スペイン語",
  "language.portugueseBrazil": "ブラジルポルトガル語",
  "language.japanese": "日本語",
  "language.german": "ドイツ語",
  "language.french": "フランス語",
  "language.polish": "ポーランド語",
  "language.chineseTraditional": "繁体字中国語",
  "language.korean": "韓国語",
  "options.title": "オプション",
  "options.language": "言語",
  "options.controllerIcons": "コントローラー表示",
  "options.controllerIcons.automatic": "自動",
  "options.controllerIcons.xbox": "XBOX",
  "options.controllerIcons.playstation": "PS",
  "options.controllerIcons.nintendo": "任天堂",
  "options.controllerIcons.generic": "汎用",
  "options.controlScheme": "操舵方式",
  "options.controlScheme.title": "操舵方式",
  "options.controlScheme.absolute": "絶対",
  "options.controlScheme.relative": "相対",
  "options.controlScheme.absoluteDetail": "方向入力で船首を向ける",
  "options.controlScheme.relativeDetail": "前で牽引・左右で旋回",
  "options.controlScheme.pointerNote": "ポインターとタッチは常に絶対操作",
  "options.keyMapping": "コントローラー配置",
  "options.keyMapping.pressKey": "キーを押す…",
  "options.keyMapping.rebind": "割り当て",
  "options.keyMapping.clear": "解除",
  "options.keyMapping.defaults": "初期設定",
  "options.keyMapping.rebindHint": "ENTERまたはクリックで割り当て　DELで解除",
  "options.keyMapping.defaultsRestored": "初期設定に戻しました",
  "options.keyMapping.movedFrom": "{action}から移動",
  "options.keyMapping.assigned": "{key}を割り当てました",
  "options.keyMapping.bindingCleared": "割り当てを解除しました",
  "options.keyMapping.bindingCancelled": "割り当てを中止しました",
  "options.keyMapping.action.steer-left": "左へ舵を切る",
  "options.keyMapping.action.steer-right": "右へ舵を切る",
  "options.keyMapping.action.steer-up": "上へ舵を切る",
  "options.keyMapping.action.steer-down": "下へ舵を切る",
  "options.keyMapping.action.fire-port": "左舷砲を撃つ",
  "options.keyMapping.action.fire-starboard": "右舷砲を撃つ",
  "options.keyMapping.action.interact": "操作",
  "options.keyMapping.action.captain-menu": "船長メニュー",
  "options.keyMapping.action.ship-info": "船と帳簿",
  "options.keyMapping.action.politics": "外交",
  "options.keyMapping.action.screenshot": "スクリーンショット",
  "options.music": "音楽",
  "options.sfx": "効果音",
  "options.mute": "ミュート",
  "options.enterFullscreen": "全画面にする",
  "options.exitFullscreen": "全画面を終了",
  "options.fullscreenUnavailable": "全画面は使用不可",
  "options.returnToMainMenu": "メインメニューへ",
  "options.quitGame": "ゲームを終了",
  "telemetry.title": "ゲーム改善に協力しますか？",
  "telemetry.body": "匿名のプレイ統計とクラッシュ報告を共有しますか？ランダムなインストールIDでプレイヤー数と継続率を測定します。氏名、アカウントID、IPアドレス、セーブデータ、広告データは保存しません。報告は3か月後に削除されます。設定でいつでも変更できます。",
  "telemetry.decline": "共有しない",
  "telemetry.accept": "匿名データを共有",
  "telemetry.option": "匿名データ",
  "telemetry.on": "オン",
  "telemetry.off": "オフ",
  "start.title": "私掠と報復",
  "start.continue": "航海を続ける",
  "start.loading": "読み込み中……",
  "start.newGame": "ニューゲーム",
  "start.startGame": "ゲーム開始",
  "start.shipBattle": "海戦",
  "start.historicalBattles": "歴史海戦",
  "battle.choose": "海戦を選ぶ",
  "start.pastVoyages": "過去の航海",
  "start.achievements": "実績",
  "start.credits": "クレジット",
  "start.saveUnreadable": "セーブを読めません",
  "start.confirmNewGame": "新しいゲームを始めますか？",
  "start.confirmWarning": "現在の航海は終了します。",
  "common.yes": "はい",
  "common.no": "いいえ",
  "common.next": "次へ",
  "common.back": "戻る",
  "common.continue": "続ける",
  "common.decline": "断る",
  "pronoun.objectFemale": "彼女",
  "pronoun.objectMale": "彼",
  "common.close": "閉じる",
  "common.page": "ページ",
  "common.days": "日",
  "common.day": "日",
  "common.loadingShip": "船を読み込み中……",
  "common.target": "標的",
  "captain.chart": "船長の海図",
  "captain.shipLedger": "船と帳簿",
  "captain.politics": "外交情勢",
  "captain.discoveries": "発見",
  "captain.achievements": "実績",
  "captain.aboard": "乗船者",
  "captain.navigation": "ウェイポイント",
  "captain.sailingBasics": "航海の基本",
  "captain.tab.map": "海図",
  "captain.tab.ship": "船",
  "captain.tab.crew": "乗員",
  "captain.tab.politics": "外交",
  "captain.tab.discoveries": "発見",
  "captain.tab.achievements": "実績",
  "captain.tab.navigation": "目的地",
  "captain.tab.sailing": "航海",
  "captain.tab.options": "設定",
  "aboard.title": "乗船者",
  "aboard.captain": "船長",
  "aboard.passenger": "乗客",
  "aboard.emissary": "使節",
  "aboard.colonyLeader": "植民隊長",
  "aboard.crewmate": "船員",
  "aboard.colonist": "入植者",
  "aboard.animal": "動物",
  "aboard.goal": "目標",
  "aboard.skill": "技能",
  "ledger.captainAccount": "船長の記録",
  "demo.voyageComplete": "体験版の航海終了",
  "demo.thanks": "プレイありがとう",
  "demo.fullVersion": "STEAMで製品版を購入",
  "outcome.lostAtSea": "海に消える",
  "outcome.neverSeenAgain": "二度と姿を見せなかった。",
  "outcome.voyageEnded": "航海終了",
  "outcome.cause": "死因",
  "outcome.causeOfDeath": "死因",
  "loadout.title": "積載を設定",
  "loadout.holdPlan": "船倉計画",
  "navigation.none": "有効なウェイポイントなし",
  "navigation.gold": "金",
  "navigation.blue": "青",
  "navigation.gray": "灰",
  "navigation.teal": "青緑",
  "navigation.foundColony": "植民地を建設",
  "navigation.openTradingPort": "貿易港を開く",
  "navigation.resupplyColony": "植民地へ補給",
  "navigation.diplomaticMission": "外交任務",
  "navigation.passengerMission": "旅客任務",
  "navigation.deliveryMission": "配達任務",
  "navigation.activeMission": "現在の任務",
  "navigation.explorerLead": "探検の手掛かり",
  "navigation.whiteWhaleSeen": "白鯨の最終目撃地",
  "navigation.reportPatron": "後援者に報告",
  "navigation.payFamilyDebt": "家の借金を返済",
  "navigation.returnVictorious": "勝利して帰郷",
  "navigation.returnHome": "帰郷",
  "navigation.securePermission": "許可を得る",
  "navigation.deliverColonyMaterials": "植民地資材を届ける",
  "navigation.deliverLongshipMaterials": "ロングシップ資材を届ける",
  "navigation.deliverWorkshopMaterials": "工房へ資材を届ける",
  "navigation.deliverGingerRoots": "ショウガの根を届ける",
  "quest.journal": "進行中の任務",
  "quest.none": "進行中の任務なし",
  "quest.mainVoyage": "主要航海",
  "quest.familyDebtOutstanding": "{city}の残債：{amount}",
  "quest.passenger": "旅客",
  "quest.delivery": "配達",
  "quest.diplomacy": "外交",
  "quest.mission": "任務",
  "quest.colony": "植民地 {city}",
  "quest.longship": "ヴァイキング船",
  "quest.matchlockIndustry": "国産火縄銃",
  "quest.caribbeanGinger": "カリブのショウガ",
  "quest.actionAt": "{city}：{action}",
  "quest.sailTo": "{city}へ航海",
  "quest.returnTo": "{city}へ戻る",
  "quest.acquireFor": "{city}用の{good} {held}/{quantity}",
  "quest.bringTo": "{good}を{quantity}個、{city}へ運ぶ",
  "quest.returnToEmbark": "{city}へ戻り遠征隊を乗せる",
  "quest.leaveAndReturn": "{city}を離れ、{good}を{quantity}個持って戻る",
  "quest.defeatAt": "{city}で{enemy}船を{count}隻倒す",
  "quest.claimAt": "{city}でロングシップを受け取る",
  "quest.buyAt": "{city}でロングシップを買う",
  "quest.fetchReadyDialogue": "{city}へ運ぶ{good}はこれで全部そろった。",
  "ship.vessel": "船",
  "ship.ledger": "帳簿",
  "ship.inventory": "所持品",
  "ship.captainLedger": "船長の帳簿",
  "ship.shipInventory": "船の所持品",
  "ship.hull": "船体",
  "ship.armor": "装甲",
  "ship.crew": "船員",
  "ship.propulsion": "推進",
  "ship.speed": "速力",
  "ship.acceleration": "加速",
  "ship.turning": "旋回",
  "ship.windward": "風上性能",
  "ship.seaworthy": "耐航性",
  "ship.water": "水",
  "ship.food": "食料",
  "ship.cargoHold": "船倉",
  "ship.holdEmpty": "船倉は空",
  "ship.itemsDocuments": "品物と書類",
  "ship.inventoryEmpty": "所持品なし",
  "ship.realizedPnl": "確定損益",
  "ship.cash": "現金",
  "ship.date": "日付",
  "ship.port": "港",
  "ship.entry": "内容",
  "ship.amount": "金額",
  "ship.balance": "残高",
  "ship.pnl": "損益",
  "ship.type": "種別",
  "ship.detail": "詳細",
  "ship.manifest": "積荷",
  "ship.held": "所持",
  "ship.average": "平均",
  "ship.doubloons": "ダブロン",
  "ship.armament": "武装",
  "ship.current": "現在",
  "ship.new": "新船",
  "ship.prize": "戦利船",
  "ship.guns": "大砲",
  "ship.atWill": "射撃可能",
  "ship.oarNoDeadZone": "櫂走／風上死角なし",
  "ship.oarSailAdaptive": "櫂帆併用／漕いで加速",
  "ship.item": "品物",
  "ship.equipment": "装備",
  "ship.delivery": "配達",
  "ship.passenger": "乗客",
  "ship.openingBalance": "開始残高",
  "ship.aboard": "船上",
  "ship.shipyardNew": "造船所／新船",
  "ship.surrenderedPrize": "降伏した戦利船",
  "discoveries.title": "発見",
  "discoveries.found": "発見数",
  "discoveries.globeMapped": "世界踏破",
  "discoveries.none": "まだ発見なし",
  "politics.title": "外交情勢",
  "politics.ally": "同盟",
  "politics.friendly": "友好",
  "politics.war": "戦争",
  "politics.neutral": "中立",
  "politics.noContact": "未接触",
  "politics.stanceToward": "各国の姿勢",
  "politics.playerStanding": "自分／交易",
  "politics.power": "勢力",
  "politics.status": "関係",
  "politics.you": "自分",
  "politics.latest": "最新",
  "politics.recent": "最近の政局",
  "politics.marque": "私掠免許",
  "politics.legendAlly": "A 同盟",
  "politics.legendWar": "W 戦争",
  "politics.legendNeutral": "- 中立  . 未接触",
  "politics.legendSuzerainty": "属国 >  朝貢 ~  同君連合 =",
  "politics.legendTrade": "% 関税  X 閉鎖  P 許可  O 開放  M 私掠",
  "politics.legendCompact": "- 中立  . 不明",
  "politics.allPowers": "全勢力",
  "politics.vassalOf": "属国",
  "politics.suzerainOf": "宗主国",
  "politics.tributaryTo": "朝貢先",
  "politics.tributeFrom": "朝貢国",
  "politics.unionWith": "同君連合",
  "politics.hostile": "敵対",
  "politics.angry": "激怒",
  "politics.cold": "冷淡",
  "politics.warm": "好意",
  "politics.favored": "厚遇",
  "politics.trusted": "信頼",
  "faction.pirate": "海賊",
  "faction.england": "イングランド",
  "faction.scotland": "スコットランド",
  "faction.france": "フランス",
  "faction.spain": "スペイン",
  "faction.portugal": "ポルトガル",
  "faction.habsburg": "ハプスブルク",
  "faction.hungary": "ハンガリー",
  "faction.ottoman": "オスマン",
  "faction.venice": "ヴェネツィア",
  "faction.genoa": "ジェノヴァ",
  "faction.papalStates": "教皇領",
  "faction.hospitallers": "聖ヨハネ騎士団",
  "faction.ming": "明",
  "faction.inca": "インカ",
  "faction.safavid": "サファヴィー",
  "faction.muscovy": "モスクワ大公国",
  "faction.polandLithuania": "ポーランド・リトアニア",
  "faction.sweden": "スウェーデン",
  "faction.denmarkNorway": "デンマーク・ノルウェー",
  "faction.songhai": "ソンガイ",
  "faction.morocco": "モロッコ",
  "faction.ethiopia": "エチオピア",
  "faction.vijayanagara": "ヴィジャヤナガル",
  "faction.gujarat": "グジャラート",
  "faction.bengal": "ベンガル",
  "faction.delhi": "デリー",
  "faction.ayutthaya": "アユタヤ",
  "faction.japan": "日本",
  "faction.joseon": "朝鮮",
  "good.hardtack": "乾パン",
  "good.freshWater": "真水",
  "good.foragedFood": "採集食料",
  "good.grain": "穀物",
  "good.fish": "魚",
  "good.whaleBlubber": "鯨脂",
  "good.beaverPelts": "ビーバー毛皮",
  "good.cheese": "チーズ",
  "good.wine": "ワイン",
  "good.oliveOil": "オリーブ油",
  "good.salt": "塩",
  "good.sugar": "砂糖",
  "good.timber": "木材",
  "good.coal": "石炭",
  "good.wool": "羊毛",
  "good.cotton": "綿",
  "good.flax": "亜麻",
  "good.iron": "鉄",
  "good.copper": "銅",
  "good.tin": "錫",
  "good.amber": "琥珀",
  "good.furs": "毛皮",
  "good.beeswax": "蜜蝋",
  "good.navalStores": "船舶用品",
  "good.sulfur": "硫黄",
  "good.arms": "槍と刀剣",
  "good.gunpowder": "火薬",
  "good.matchlocks": "火縄銃",
  "good.linenCloth": "リネン布",
  "good.woolCloth": "毛織物",
  "good.cottonCloth": "綿布",
  "good.paper": "紙",
  "good.printedBooks": "印刷書",
  "good.silk": "生糸",
  "good.silkCloth": "絹織物",
  "good.lacquerware": "漆器",
  "good.ginseng": "高麗人参",
  "good.pepper": "胡椒",
  "good.cinnamon": "シナモン",
  "good.cloves": "クローブ",
  "good.nutmeg": "ナツメグ",
  "good.ginger": "ショウガ",
  "good.tea": "茶",
  "good.coffee": "コーヒー",
  "good.cacao": "カカオ",
  "good.dyes": "染料",
  "good.indigo": "藍",
  "good.porcelain": "磁器",
  "good.glassware": "ガラス器",
  "good.carpets": "絨毯",
  "good.artwork": "美術品",
  "good.perfume": "香水",
  "good.ivory": "象牙",
  "good.silver": "銀",
  "good.gold": "金",
  "voyages.title": "過去の航海",
  "voyages.register": "歴代船長名簿",
  "voyages.voyages": "航海回数",
  "voyages.totalDays": "合計日数",
  "voyages.longest": "最長航海",
  "voyages.totalEarned": "総収入",
  "voyages.mostEarned": "最高収入",
  "voyages.richestEnding": "最高残高",
  "voyages.mostDiscoveries": "最多発見",
  "voyages.winDeathQuitDemo": "勝利／死亡／中断／体験版",
  "voyages.none": "過去の航海なし",
  "voyages.home": "故郷",
  "voyages.resultGoal": "結果／目標",
  "voyages.lastVessel": "最後の船",
  "voyages.daysMapped": "日数／世界踏破",
  "voyages.earnedNet": "収入／純益",
  "voyages.finalTradePnl": "残高／交易損益",
  "voyages.discoveryPortsWorld": "発見／港／世界",
  "voyages.questsMarques": "任務／私掠免許",
  "voyages.crewLostPiracy": "船員喪失／海賊行為",
  "voyages.fate": "運命",
  "intro.papers": "船長の書類",
  "intro.homePort": "母港",
  "intro.nationality": "国籍",
  "intro.religion": "宗教",
  "intro.born": "生年月日",
  "intro.age": "年齢",
  "intro.sex": "性別",
  "intro.male": "男",
  "intro.female": "女",
  "intro.begin": "出航",
  "tutorial.turnSail": "方向転換と帆走",
  "tutorial.upwind": "風上へ進む",
  "tutorial.rowing": "櫂走",
  "tutorial.escapeShore": "岸から脱出",
  "tutorial.takeHelm": "舵を取る",
  "tutorial.pressHold": "長押し",
  "tutorial.tiltHold": "スティックを倒す",
  "tutorial.touchHold": "タッチ長押し",
  "tutorial.clickHold": "クリック長押し",
  "tutorial.turnBow": "船首を回す",
  "tutorial.wind": "風向",
  "tutorial.tack": "タッキング",
  "tutorial.holdRow": "長押しで漕ぐ",
  "tutorial.releaseRest": "離すと休む",
  "tutorial.haul": "曳航",
  "tutorial.openWater": "開水面",
  "tutorial.touchSteer": "船の周囲をタッチして長押しします。船首が指の方向へ向きます。航行中も押し続けてください。",
  "tutorial.mouseSteer": "船の周囲をクリックして長押しします。船首がポインターの方向へ向きます。航行中も押し続けてください。",
  "tutorial.keyboardSteer": "WASDまたは矢印キーを長押しします。船首がその方向へ向きます。航行中も押し続けてください。",
  "tutorial.controllerSteer": "左スティックを倒したままにします。船首がその方向へ向きます。航行中も倒し続けてください。",
  "tutorial.tacking": "ほとんどの帆船は風上へ直進できません。風向の左右どちらかへ進み、交互に切り返してください。このジグザグ航法をタッキングと呼びます。",
  "tutorial.touchRow": "櫂のある船では、進みたい方向をタッチして長押しすると漕ぎます。離すと漕ぎ手は休みます。船員が多いほど櫂は強くなりますが、食料の消費も少し早まります。",
  "tutorial.mouseRow": "櫂のある船では、進みたい方向をクリックして長押しすると漕ぎます。離すと漕ぎ手は休みます。船員が多いほど櫂は強くなりますが、食料の消費も少し早まります。",
  "tutorial.keyboardRowAbsolute": "櫂のある船では、方向キーを長押しするとその方向へ漕ぎます。離すと漕ぎ手は休みます。船員が多いほど櫂は強くなりますが、食料の消費も少し早まります。",
  "tutorial.keyboardRowRelative": "櫂のある船では、前進キーを長押しすると漕ぎます。離すと漕ぎ手は休みます。船員が多いほど櫂は強くなりますが、食料の消費も少し早まります。",
  "tutorial.controllerRowAbsolute": "櫂のある船では、左スティックを進みたい方向へ倒し続けると漕ぎます。離すと漕ぎ手は休みます。船員が多いほど櫂は強くなりますが、食料の消費も少し早まります。",
  "tutorial.controllerRowRelative": "櫂のある船では、左スティックを前へ倒し続けると漕ぎます。離すと漕ぎ手は休みます。船員が多いほど櫂は強くなりますが、食料の消費も少し早まります。",
  "tutorial.touchHaul": "風で川岸や海岸に押し付けられたら、開水面の方向をタッチして長押しします。船員が岸沿いにゆっくり船を曳きます。",
  "tutorial.mouseHaul": "風で川岸や海岸に押し付けられたら、開水面の方向をクリックして長押しします。船員が岸沿いにゆっくり船を曳きます。",
  "tutorial.keyboardHaul": "風で川岸や海岸に押し付けられたら、開水面へ向かう方向キーを長押しします。船員が岸沿いにゆっくり船を曳きます。",
  "tutorial.controllerHaul": "風で川岸や海岸に押し付けられたら、左スティックを開水面へ倒し続けます。船員が岸沿いにゆっくり船を曳きます。",
  "dialogue.leavePort": "出港",
  "dialogue.buy": "購入",
  "dialogue.sell": "売却",
  "dialogue.trade": "交易",
  "dialogue.accept": "引き受ける",
  "dialogue.capital": "首都",
  "status.mapped": "踏破済み",
  "status.drinkableWaterLow": "飲料水残りわずか",
  "status.sunset": "日没",
  "status.sunrise": "日の出",
  "storm.manOverboardLabel": "船員が落水",
  "storm.manOverboardFirst": "面舵一杯！大波で船員が海へ投げ出された。海に呑まれる前に船を寄せろ。",
  "storm.manOverboardNoticeOne": "船員が落水",
  "storm.manOverboardNoticeMany": "船員{count}名が落水",
  "storm.manOverboardRecoveredOne": "船員を救助",
  "storm.manOverboardRecoveredMany": "船員{count}名を救助",
  "storm.manOverboardDrownedOne": "船員1名を失った",
  "storm.manOverboardDrownedMany": "船員{count}名を海で失った",
  "hud.tooltip.localDate": "現地日付：{date}",
  "hud.tooltip.doubloons": "ダブロン：{count}",
  "hud.tooltip.hull": "船体強度：{current}/{maximum}",
  "hud.tooltip.waterDaysOne": "飲料水はあと{days}日分",
  "hud.tooltip.waterDaysMany": "飲料水はあと{days}日分",
  "hud.tooltip.foodDaysOne": "食料はあと{days}日分",
  "hud.tooltip.foodDaysMany": "食料はあと{days}日分",
  "hud.tooltip.crewCountOne": "乗組員{count}名",
  "hud.tooltip.crewCountMany": "乗組員{count}名",
  "hud.tooltip.passengerCountOne": "乗客{count}名",
  "hud.tooltip.passengerCountMany": "乗客{count}名",
  "hud.tooltip.aboardCrew": "乗船中：{crew}",
  "hud.tooltip.aboardCrewPassengers": "乗船中：{crew}＋{passengers}",
  "hud.tooltip.animalCompanion.panda": "パンダ1頭",
  "hud.tooltip.animalCompanion.penguin": "ペンギン1羽",
  "hud.tooltip.animalCompanion.raccoon": "アライグマ1匹",
  "hud.tooltip.aboardCrewAnimals": "乗船中：{crew}＋{animals}",
  "hud.tooltip.aboardCrewPassengersAnimals": "乗船中：{crew}＋{passengers}＋{animals}",
  "discovery.greatBarrierReef.name": "グレート・バリア・リーフ",
  "discovery.greatBarrierReef.notice": "グレート・バリア・リーフを発見した",
  "discovery.greatBarrierReef.detail": "オーストラリア北東部、珊瑚海",
  "discovery.greatBarrierReef.captain": "海の下が生きている――見渡す限り、珊瑚の庭が続いている！",
  "discovery.greatBarrierReef.reportCaptain": "オーストラリア沖を何日も進むあいだ、船の下で海の色が変わり続けました。水面のすぐ下には、魚の群れる珊瑚の庭が見渡す限り続いていたのです。",
  "discovery.greatBarrierReef.reportPatron": "王が築いたどの城壁よりも長い、生きた防壁か。すべての水路を慎重に記せ。海中の驚異は、船乗りにとって脅威でもある。",
  "status.loading": "『Marque & Reprisal』読み込み中……",
  "aria.worldMap": "世界地図",
  "aria.shipBattleLake": "海戦水域",
  "aria.historicalBattle": "歴史海戦",
  "aria.canvas": "Marque & Reprisal {surface}、{width}×{height}"
});

const CATALOGS = Object.freeze({
  [LANGUAGE_ENGLISH]: ENGLISH,
  [LANGUAGE_CHINESE_SIMPLIFIED]: CHINESE_SIMPLIFIED,
  [LANGUAGE_RUSSIAN]: Object.freeze(RUSSIAN),
  [LANGUAGE_SPANISH]: Object.freeze(SPANISH),
  [LANGUAGE_PORTUGUESE_BRAZIL]: Object.freeze(PORTUGUESE_BRAZIL),
  [LANGUAGE_JAPANESE]: JAPANESE,
  [LANGUAGE_GERMAN]: Object.freeze(GERMAN),
  [LANGUAGE_FRENCH]: Object.freeze(FRENCH),
  [LANGUAGE_POLISH]: Object.freeze(POLISH),
  [LANGUAGE_CHINESE_TRADITIONAL]: Object.freeze(CHINESE_TRADITIONAL),
  [LANGUAGE_KOREAN]: Object.freeze(KOREAN)
});

const ENGLISH_PHRASE_KEYS = Object.freeze(new Map(
  Object.entries(ENGLISH).map(([key, value]) => [value, key])
));
const LOCALIZED_TEXT_CACHE_LIMIT = 32_768;
const localizedTextCache = new Map();

const EMBEDDED_PHRASES = Object.freeze(
  Object.entries(ENGLISH)
    .filter(([key]) => key.startsWith("good."))
    .sort((left, right) => right[1].length - left[1].length)
    .map(([key, value]) => Object.freeze({
      key,
      expression: new RegExp(escapeRegularExpression(value), "gi")
    }))
);

const DYNAMIC_TEMPLATE_KEYS = Object.freeze([
  "page",
  "voyage",
  "mapped",
  "manifest",
  "ledger",
  "inventory",
  "waterDays",
  "foodDays",
  "days",
  "held",
  "cash",
  "pnl",
  "realizedPnl",
  "averageEmpty",
  "average",
  "rations",
  "sailDeadZone",
  "doubloons",
  "latest"
]);

const DYNAMIC_TEMPLATES = Object.freeze({
  [LANGUAGE_CHINESE_SIMPLIFIED]: dynamicTemplates([
    "第{0}/{1}页", "第{0}次航程", "已测绘 {0}", "货单 {0}/{1}", "账簿 {0}/{1}",
    "物品 {0}/{1}", "淡水 {0}天", "食物 {0}天", "{0}天", "持有 {0}",
    "现款 {0}", "盈亏 {0}", "已结盈亏 {0}", "均价 --", "均价 {0}",
    "{0}份口粮", "风帆／迎风死区{0}度", "{0} 达布隆", "最新：{0}"
  ]),
  [LANGUAGE_RUSSIAN]: dynamicTemplates([
    "СТР. {0}/{1}", "ПЛАВАНИЕ {0}", "КАРТА {0}", "МАНИФЕСТ {0}/{1}", "КНИГА {0}/{1}",
    "ИНВЕНТАРЬ {0}/{1}", "ВОДА {0} ДН.", "ЕДА {0} ДН.", "{0} ДН.", "В ТРЮМЕ {0}",
    "НАЛИЧНЫЕ {0}", "П/У {0}", "ПОЛУЧЕННАЯ П/У {0}", "СРЕД. --", "СРЕД. {0}",
    "{0} ПАЙКОВ", "ПАРУС / МЁРТВАЯ ЗОНА {0}°", "{0} ДУБЛОНОВ", "ПОСЛЕДНЕЕ: {0}"
  ]),
  [LANGUAGE_SPANISH]: dynamicTemplates([
    "PÁG. {0}/{1}", "VIAJE {0}", "MAPA {0}", "MANIFIESTO {0}/{1}", "LIBRO {0}/{1}",
    "INVENTARIO {0}/{1}", "AGUA {0} DÍAS", "COMIDA {0} DÍAS", "{0} DÍAS", "EN BODEGA {0}",
    "EFECTIVO {0}", "G/P {0}", "G/P REALIZADA {0}", "PROM. --", "PROM. {0}",
    "{0} RACIONES", "VELA / ZONA MUERTA {0}°", "{0} DOBLONES", "ÚLTIMO: {0}"
  ]),
  [LANGUAGE_PORTUGUESE_BRAZIL]: dynamicTemplates([
    "PÁG. {0}/{1}", "VIAGEM {0}", "MAPEADO {0}", "MANIFESTO {0}/{1}", "LIVRO {0}/{1}",
    "INVENTÁRIO {0}/{1}", "ÁGUA {0} DIAS", "COMIDA {0} DIAS", "{0} DIAS", "EM POSSE {0}",
    "DINHEIRO {0}", "L/P {0}", "L/P REALIZADO {0}", "MÉDIA --", "MÉDIA {0}",
    "{0} RAÇÕES", "VELA / ZONA MORTA {0}°", "{0} DOBRÕES", "RECENTE: {0}"
  ]),
  [LANGUAGE_JAPANESE]: dynamicTemplates([
    "{0}/{1}頁", "第{0}航海", "踏破済み {0}", "積荷 {0}/{1}", "帳簿 {0}/{1}",
    "所持品 {0}/{1}", "水 {0}日", "食料 {0}日", "{0}日", "{0}点",
    "現金 {0}", "損益 {0}", "確定損益 {0}", "平均 --", "平均 {0}",
    "{0}食", "帆走／風上死角{0}度", "{0}ダブロン", "最新：{0}"
  ]),
  [LANGUAGE_GERMAN]: dynamicTemplates([
    "SEITE {0}/{1}", "REISE {0}", "KARTIERT {0}", "MANIFEST {0}/{1}", "JOURNAL {0}/{1}",
    "INVENTAR {0}/{1}", "WASSER {0} TAGE", "PROVIANT {0} TAGE", "{0} TAGE", "AN BORD {0}",
    "BARGELD {0}", "G/V {0}", "REALISIERTER G/V {0}", "Ø --", "Ø {0}",
    "{0} RATIONEN", "SEGEL / TOTWINKEL {0}°", "{0} DUBLONEN", "NEUESTES: {0}"
  ]),
  [LANGUAGE_FRENCH]: dynamicTemplates([
    "PAGE {0}/{1}", "VOYAGE {0}", "CARTOGRAPHIÉ {0}", "MANIFESTE {0}/{1}", "LIVRE {0}/{1}",
    "INVENTAIRE {0}/{1}", "EAU {0} JOURS", "VIVRES {0} JOURS", "{0} JOURS", "DÉTENU {0}",
    "ESPÈCES {0}", "B/P {0}", "B/P RÉALISÉ {0}", "MOY. --", "MOY. {0}",
    "{0} RATIONS", "VOILE / ANGLE MORT {0}°", "{0} DOUBLONS", "DERNIER : {0}"
  ]),
  [LANGUAGE_POLISH]: dynamicTemplates([
    "STR. {0}/{1}", "REJS {0}", "ZMAPOWANO {0}", "MANIFEST {0}/{1}", "KSIĘGA {0}/{1}",
    "INWENTARZ {0}/{1}", "WODA {0} DNI", "ŻYWNOŚĆ {0} DNI", "{0} DNI", "W ŁADOWNI {0}",
    "GOTÓWKA {0}", "Z/S {0}", "ZREALIZOWANY Z/S {0}", "ŚR. --", "ŚR. {0}",
    "{0} RACJI", "ŻAGIEL / MARTWA STREFA {0}°", "{0} DUBLONÓW", "OSTATNIE: {0}"
  ]),
  [LANGUAGE_CHINESE_TRADITIONAL]: dynamicTemplates([
    "第{0}/{1}頁", "第{0}次航程", "已測繪 {0}", "貨單 {0}/{1}", "帳簿 {0}/{1}",
    "物品 {0}/{1}", "淡水 {0}天", "食物 {0}天", "{0}天", "持有 {0}",
    "現款 {0}", "盈虧 {0}", "已結盈虧 {0}", "均價 --", "均價 {0}",
    "{0}份口糧", "風帆／迎風死角{0}度", "{0} 達布隆", "最新：{0}"
  ]),
  [LANGUAGE_KOREAN]: dynamicTemplates([
    "{0}/{1}쪽", "항해 {0}", "지도 {0}", "적하 {0}/{1}", "원장 {0}/{1}",
    "소지품 {0}/{1}", "식수 {0}일", "식량 {0}일", "{0}일", "보유 {0}",
    "현금 {0}", "손익 {0}", "실현 손익 {0}", "평균 --", "평균 {0}",
    "{0}식", "돛 / 맞바람 사각 {0}도", "두블룬 {0}개", "최근: {0}"
  ])
});

const DYNAMIC_PATTERNS = Object.freeze([
  dynamicPattern(/^PAGE (\d+)\/(\d+)$/, "page"),
  dynamicPattern(/^VOYAGE (\d+)$/, "voyage"),
  dynamicPattern(/^MAPPED (.+)$/, "mapped"),
  dynamicPattern(/^MANIFEST (\d+)\/(\d+)$/, "manifest"),
  dynamicPattern(/^LEDGER (\d+)\/(\d+)$/, "ledger"),
  dynamicPattern(/^INVENTORY (\d+)\/(\d+)$/, "inventory"),
  dynamicPattern(/^WATER (.+)D$/, "waterDays"),
  dynamicPattern(/^FOOD (.+)D$/, "foodDays"),
  dynamicPattern(/^(\d+) DAYS$/, "days"),
  dynamicPattern(/^(\d+) HELD$/, "held"),
  dynamicPattern(/^CASH (.+) DB$/, "cash"),
  dynamicPattern(/^P\/L (.+) DB$/, "pnl"),
  dynamicPattern(/^REALIZED P\/L (.+) DB$/, "realizedPnl"),
  dynamicPattern(/^AVG --$/, "averageEmpty"),
  dynamicPattern(/^AVG (.+) DB$/, "average"),
  dynamicPattern(/^(.+) RATIONS$/, "rations"),
  dynamicPattern(/^SAIL \/ (.+) DEG$/, "sailDeadZone"),
  dynamicPattern(/^(.+) DOUBLOONS$/, "doubloons"),
  dynamicPattern(/^LATEST (.+)$/, "latest")
]);

export function normalizeLanguage(value, fallback = LANGUAGE_ENGLISH) {
  if (SUPPORTED_LANGUAGES.some((entry) => entry.id === value)) return value;
  if (typeof value === "string") {
    const normalized = value.trim().toLowerCase();
    if (normalized === "zh-tw" || normalized === "zh-hk" || normalized === "zh-mo" || normalized === "zh-hant") {
      return LANGUAGE_CHINESE_TRADITIONAL;
    }
    if (normalized === "zh" || normalized === "zh-cn" || normalized === "zh-sg" || normalized === "zh-hans") {
      return LANGUAGE_CHINESE_SIMPLIFIED;
    }
    if (normalized === "pt" || normalized === "pt-br" || normalized === "pt_br") {
      return LANGUAGE_PORTUGUESE_BRAZIL;
    }
    if (normalized === "ru" || normalized.startsWith("ru-")) return LANGUAGE_RUSSIAN;
    if (normalized === "es" || normalized.startsWith("es-")) return LANGUAGE_SPANISH;
    if (normalized === "ja" || normalized.startsWith("ja-")) return LANGUAGE_JAPANESE;
    if (normalized === "de" || normalized.startsWith("de-")) return LANGUAGE_GERMAN;
    if (normalized === "fr" || normalized.startsWith("fr-")) return LANGUAGE_FRENCH;
    if (normalized === "pl" || normalized.startsWith("pl-")) return LANGUAGE_POLISH;
    if (normalized === "ko" || normalized.startsWith("ko-")) return LANGUAGE_KOREAN;
    if (normalized === "en" || normalized.startsWith("en-")) return LANGUAGE_ENGLISH;
  }
  if (fallback === value) return LANGUAGE_ENGLISH;
  return normalizeLanguage(fallback, LANGUAGE_ENGLISH);
}

export function translate(language, key, replacements = {}) {
  const locale = normalizeLanguage(language);
  const template = CATALOGS[locale][key] ?? ENGLISH[key];
  if (template === undefined) throw new Error(`Unknown localization key: ${key}`);
  return interpolate(template, replacements);
}

export function localizeText(language, text) {
  if (typeof text !== "string") throw new Error(`Localized text must be a string: ${text}`);
  const locale = normalizeLanguage(language);
  if (locale === LANGUAGE_ENGLISH || text.length === 0) return text;
  const cacheKey = `${locale}\u0000${text}`;
  const cached = localizedTextCache.get(cacheKey);
  if (cached !== undefined) return cached;
  const localized = localizeTextUncached(locale, text);
  if (localizedTextCache.size >= LOCALIZED_TEXT_CACHE_LIMIT) localizedTextCache.clear();
  localizedTextCache.set(cacheKey, localized);
  return localized;
}

function localizeTextUncached(locale, text) {
  const exactKey = ENGLISH_PHRASE_KEYS.get(text);
  if (exactKey) return translate(locale, exactKey);
  for (const pattern of DYNAMIC_PATTERNS) {
    const match = text.match(pattern.expression);
    const template = DYNAMIC_TEMPLATES[locale]?.[pattern.templateKey];
    if (match && template) {
      return localizeEmbeddedPhrases(locale, formatDynamicTemplate(template, match.slice(1)));
    }
  }
  const gameplayText = localizeGameplayScreenText(
    locale,
    text,
    (capture) => localizeText(locale, capture)
  );
  if (gameplayText !== text) return localizeEmbeddedPhrases(locale, gameplayText);
  const composedText = localizeComposedScreenText(locale, text);
  if (composedText !== text) return composedText;
  return localizeEmbeddedPhrases(locale, text);
}

function localizeComposedScreenText(locale, text) {
  const parts = text.split(/(\s{2,})/);
  if (parts.length === 1) return text;
  let changed = false;
  const localized = parts.map((part, index) => {
    if (index % 2 === 1) return part;
    const result = localizeText(locale, part);
    if (result !== part) changed = true;
    return result;
  });
  return changed ? localized.join("") : text;
}

export function languageFontProfile(language) {
  const locale = normalizeLanguage(language);
  if (locale === LANGUAGE_KOREAN) {
    return Object.freeze({
      smallFont: '11px "Galmuri11", monospace',
      dialogueFont: '11px "Galmuri11", monospace',
      fontFamily: "Galmuri11",
      fontSize: 11,
      lineHeight: 13,
      detailLineHeight: 13,
      tableRowHeight: 13
    });
  }
  if (new Set([
    LANGUAGE_CHINESE_SIMPLIFIED,
    LANGUAGE_CHINESE_TRADITIONAL,
    LANGUAGE_JAPANESE,
    LANGUAGE_RUSSIAN,
    LANGUAGE_POLISH
  ]).has(locale)) {
    return Object.freeze({
      smallFont: '12px "zpix", monospace',
      dialogueFont: '12px "zpix", monospace',
      fontFamily: "zpix",
      fontSize: 12,
      lineHeight: 14,
      detailLineHeight: 14,
      tableRowHeight: 14
    });
  }
  return Object.freeze({
    smallFont: '8px "Silkscreen", monospace',
    dialogueFont: '8px "Dogica", monospace',
    fontFamily: "Silkscreen",
    fontSize: 8,
    lineHeight: 10,
    detailLineHeight: 10,
    tableRowHeight: 11
  });
}

export function languageTitleFont(language, text) {
  if (typeof text !== "string" || text.length === 0) {
    throw new Error("Localized title must be a non-empty string");
  }
  return /^[\x20-\x7e]+$/.test(text)
    ? '8px "Pixel Pirate", monospace'
    : languageFontProfile(language).smallFont;
}

export function languageHasCjkMetrics(language) {
  const locale = normalizeLanguage(language);
  return new Set([
    LANGUAGE_CHINESE_SIMPLIFIED,
    LANGUAGE_CHINESE_TRADITIONAL,
    LANGUAGE_JAPANESE,
    LANGUAGE_KOREAN
  ]).has(locale);
}

export function languageUsesTallPixelMetrics(language) {
  return languageFontProfile(language).fontSize > 8;
}

export function textContainsCjk(text) {
  return /[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Hangul}]/u.test(String(text));
}

export function textUsesLocaleGlyphs(language, text) {
  const locale = normalizeLanguage(language);
  const value = String(text);
  if (languageHasCjkMetrics(locale)) return textContainsCjk(value);
  if (locale === LANGUAGE_RUSSIAN) return /\p{Script=Cyrillic}/u.test(value);
  if (locale === LANGUAGE_POLISH) return /[ĄĆĘŁŃÓŚŹŻąćęłńóśźż]/u.test(value);
  return false;
}

export function nextLanguage(language, direction = 1) {
  if (!Number.isInteger(direction) || direction === 0) {
    throw new Error(`Language step must be a non-zero integer: ${direction}`);
  }
  const current = normalizeLanguage(language);
  const index = SUPPORTED_LANGUAGES.findIndex((entry) => entry.id === current);
  const nextIndex = (index + Math.sign(direction) + SUPPORTED_LANGUAGES.length) % SUPPORTED_LANGUAGES.length;
  return SUPPORTED_LANGUAGES[nextIndex].id;
}

export function localizationCatalog(language) {
  return CATALOGS[normalizeLanguage(language)];
}

export function languageNativeLabel(language) {
  const locale = normalizeLanguage(language);
  const entry = SUPPORTED_LANGUAGES.find((candidate) => candidate.id === locale);
  if (!entry) throw new Error(`Supported language is missing metadata: ${locale}`);
  return entry.nativeLabel;
}

function dynamicTemplates(values) {
  if (!Array.isArray(values) || values.length !== DYNAMIC_TEMPLATE_KEYS.length) {
    throw new Error(`Expected ${DYNAMIC_TEMPLATE_KEYS.length} dynamic localization templates`);
  }
  return Object.freeze(Object.fromEntries(
    DYNAMIC_TEMPLATE_KEYS.map((key, index) => [key, values[index]])
  ));
}

function dynamicPattern(expression, templateKey) {
  if (!DYNAMIC_TEMPLATE_KEYS.includes(templateKey)) {
    throw new Error(`Unknown dynamic localization template: ${templateKey}`);
  }
  return Object.freeze({ expression, templateKey });
}

function formatDynamicTemplate(template, values) {
  return template.replace(/\{(\d+)\}/g, (_match, index) => {
    const value = values[Number(index)];
    if (value === undefined) throw new Error(`Missing dynamic localization replacement: ${index}`);
    return value;
  });
}

function localizeEmbeddedPhrases(locale, text) {
  let localized = text;
  for (const phrase of EMBEDDED_PHRASES) {
    localized = localized.replace(phrase.expression, translate(locale, phrase.key));
  }
  return localized;
}

function escapeRegularExpression(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function interpolate(template, replacements) {
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (_match, key) => {
    if (!(key in replacements)) throw new Error(`Missing localization replacement: ${key}`);
    return String(replacements[key]);
  });
}
