export const NAME_CULTURE_LABELS = Object.freeze({
  english: "English",
  irish: "Irish",
  scottish: "Scottish",
  french: "French",
  spanish: "Spanish",
  basque: "Basque",
  portuguese: "Portuguese",
  italian: "Italian",
  germanic: "German",
  czech: "Czech",
  nordic: "Norse",
  icelandic: "Icelandic",
  finnish: "Finnish",
  slavic: "Slavic",
  polish: "Polish",
  lithuanian: "Lithuanian",
  russian: "Russian",
  ruthenian: "Ruthenian",
  hungarian: "Hungarian",
  albanian: "Albanian",
  bulgarian: "Bulgarian",
  romanian: "Romanian",
  serbian: "Serbian",
  greek: "Greek",
  ottoman: "Ottoman",
  crimeanTatar: "Crimean Tatar",
  tatar: "Tatar",
  arabic: "Arab",
  centralAsian: "Central Asian",
  persian: "Persian",
  indoMuslim: "South Asian Muslim",
  jewish: "Jewish",
  sikh: "Sikh",
  southAsian: "South Asian",
  northIndian: "North Indian",
  gujarati: "Gujarati",
  bengali: "Bengali",
  southIndian: "South Indian",
  malayali: "Malayali",
  sinhalese: "Sinhalese",
  southeastAsian: "Southeast Asian",
  malay: "Malay",
  javanese: "Javanese",
  malukan: "Malukan",
  cebuano: "Cebuano",
  thai: "Thai",
  monBurmese: "Mon-Burmese",
  vietnamese: "Vietnamese",
  cham: "Cham",
  lao: "Lao",
  polynesian: "Polynesian",
  chinese: "Chinese",
  japanese: "Japanese",
  ryukyuan: "Ryukyuan",
  ainu: "Ainu",
  korean: "Korean",
  westAfrican: "West African",
  mande: "Mande",
  yoruba: "Yoruba",
  hausa: "Hausa",
  kanuri: "Kanuri",
  kongo: "Kongo",
  khoikhoi: "Khoikhoi",
  eastAfrican: "East African",
  swahili: "Swahili",
  somali: "Somali",
  ethiopian: "Ethiopian",
  shona: "Shona",
  northwestCoast: "Northwest Coast",
  wendat: "Wendat",
  shawnee: "Shawnee",
  taino: "Taino",
  tupi: "Tupi",
  maya: "Maya",
  purepecha: "Purepecha",
  nahua: "Nahua",
  andean: "Andean",
  maritime: "Maritime"
});

export const NAME_CULTURE_IDS = Object.freeze(Object.keys(NAME_CULTURE_LABELS));

export function assertNameCultureId(cultureId) {
  if (typeof cultureId !== "string" || !Object.hasOwn(NAME_CULTURE_LABELS, cultureId)) {
    throw new Error(`Unknown character name culture: ${cultureId}`);
  }
  return cultureId;
}
