export const SHIP_SPRITE_FRAME_SIZE = 47;
export const SHIP_SPRITE_RENDER_SIZE = SHIP_SPRITE_FRAME_SIZE * 2;
export const SHIP_SHADOW_FRAME_SIZE = SHIP_SPRITE_FRAME_SIZE * 2 + 1;
export const SHIP_SPRITE_SHEET_COLS = 4;
export const SHIP_SPRITE_HEADINGS = 16;
